// 라이더-웨이트-스미스 78장. 이미지는 1909년 판본(퍼블릭 도메인).
// 글은 두 벌입니다. u = 정방향, r = 역방향, k = 키워드,
// t = 주제별 한 줄(연애/일/돈/관계). 영어는 번역이 아니라 따로 썼습니다.
export const CARDS = [

  // ── 메이저 아르카나 ──
  { id:'major-00', arcana:'major', num:0,
    name:{ ko:'바보', en:'The Fool' },
    k:{ ko:['시작','자유','순수','모험'], en:['Beginnings','Freedom','Innocence','Leap'] },
    u:{ ko:'아무것도 정해지지 않은 자리에 서 있습니다. 경험이 없다는 것이 약점이 아니라 밑천인 순간이에요. 계산을 접고 첫발을 내딛으라는 신호입니다.', en:'Nothing is settled yet, and that is the point. Having no experience is capital here, not a flaw. Step off before you finish calculating.' },
    r:{ ko:'무모함과 회피가 겹쳐 있습니다. 준비 없이 뛰어들거나, 반대로 영원히 출발선에 머무는 중일 수 있어요. 지금 필요한 건 최소한의 계획입니다.', en:'Recklessness and avoidance wear the same face. You are either jumping without ground or standing at the line forever. A minimal plan is what is missing.' },
    t:{ love:{ ko:'시작하는 용기와 무모함이 종이 한 장 차이입니다. 상대의 속도를 함께 보면 도움이 됩니다.', en:'The line between courage and recklessness is thin here. It helps to watch the other person\'s pace as well as your own.' },
        work:{ ko:'경험보다 발을 떼는 쪽이 중요한 자리입니다. 최소한의 계획만 세워두면 좋습니다.', en:'Taking the first step matters more than experience. A minimal plan is enough to start.' },
        money:{ ko:'익숙지 않은 곳에 마음이 갑니다. 잃어도 괜찮을 만큼인지 먼저 보면 편합니다.', en:'Something unfamiliar is pulling at you. Check whether it is an amount you can afford to lose.' },
        rel:{ ko:'낯선 사람과의 거리가 주제입니다. 첫인상만으로 정하지 않으면 좋습니다.', en:'This is about distance with someone you barely know. Try not to settle it on a first impression.' } } },
  { id:'major-01', arcana:'major', num:1,
    name:{ ko:'마법사', en:'The Magician' },
    k:{ ko:['의지','실행력','재능','집중'], en:['Will','Execution','Skill','Focus'] },
    u:{ ko:'필요한 도구가 이미 손안에 다 있습니다. 아이디어를 현실로 옮길 힘과 타이밍이 맞아떨어지는 시기예요. 선언하고 시작하세요.', en:'Every tool you need is already on the table. Capability and timing line up. Say it out loud and begin.' },
    r:{ ko:'재능이 흩어지거나 잘못된 곳에 쓰이고 있습니다. 말만 앞서거나 스스로를 속이고 있지는 않은지 점검할 때입니다.', en:'Skill is scattered or aimed at the wrong thing. Check whether you are talking more than doing, or telling yourself a story.' },
    t:{ love:{ ko:'먼저 움직일 것인가가 관건입니다. 마음과 말이 같은지 보면 도움이 됩니다.', en:'Whether you move first is the question. It helps if your words and your intent match.' },
        work:{ ko:'가진 재료로 무엇을 만들지의 문제입니다. 흩어진 일을 하나로 모으면 좋습니다.', en:'This is about what you build from materials already at hand. Pull scattered work into one line.' },
        money:{ ko:'수완이 통하는지가 갈립니다. 자신을 과신하고 있지 않은지 보면 편합니다.', en:'Resourcefulness can carry this. Watch that confidence does not turn into overreach.' },
        rel:{ ko:'내가 판을 만드는 쪽인지가 주제입니다.', en:'The theme is whether you are the one shaping the situation.' } } },
  { id:'major-02', arcana:'major', num:2,
    name:{ ko:'여사제', en:'The High Priestess' },
    k:{ ko:['직관','비밀','내면','기다림'], en:['Intuition','Secrets','Inner voice','Waiting'] },
    u:{ ko:'답은 밖이 아니라 안에 있습니다. 아직 드러나지 않은 정보가 있으니 서두르지 말고 조용히 관찰하세요. 직감이 유난히 정확한 시기입니다.', en:'The answer is inside rather than outside. Something is still hidden, so watch quietly instead of rushing. Instinct is unusually accurate now.' },
    r:{ ko:'내면의 목소리를 무시하거나, 숨겨야 할 것과 나눠야 할 것을 혼동하고 있습니다. 감춰진 사실이 곧 드러날 수 있어요.', en:'You are ignoring your own voice, or confusing what should stay private with what should be shared. Something concealed may surface soon.' },
    t:{ love:{ ko:'아직 꺼내지 않은 마음이 핵심입니다. 서두르지 않고 지켜보면 도움이 됩니다.', en:'What has not been said yet is the heart of it. Watching quietly, without rushing, helps.' },
        work:{ ko:'드러나지 않은 사정이 있는지가 관건입니다. 결론을 미뤄두면 좋습니다.', en:'The question is whether facts are still hidden. Holding off on a conclusion helps.' },
        money:{ ko:'확실치 않은 정보가 걸립니다. 근거를 확인하기 전까지 물러나 있으면 편합니다.', en:'Uncertain information is the issue. Stay back until you can verify the basis.' },
        rel:{ ko:'상대가 다 보여주지 않는 부분이 주제입니다.', en:'The subject is the part the other person is not showing.' } } },
  { id:'major-03', arcana:'major', num:3,
    name:{ ko:'여황제', en:'The Empress' },
    k:{ ko:['풍요','돌봄','창조','감각'], en:['Abundance','Care','Creation','Senses'] },
    u:{ ko:'키워온 것이 열매를 맺습니다. 관계든 일이든 넉넉하게 품고 돌볼 여유가 생겨요. 몸의 감각과 아름다움을 즐겨도 좋은 때입니다.', en:'What you nurtured bears fruit. There is room now to hold and tend, in work or in a bond. Enjoy the body and the beauty around you.' },
    r:{ ko:'과보호이거나 방치입니다. 남을 돌보느라 자신이 비어가고 있을 수 있어요. 창작이 막혔다면 쉬는 것이 답입니다.', en:'Either smothering or neglect. You may be emptying yourself caring for others. If creating feels blocked, rest is the answer.' },
    t:{ love:{ ko:'품는 마음과 여유가 주제입니다. 몸과 마음의 상태를 함께 챙기면 도움이 됩니다.', en:'Holding and having room is the theme. Look after your body and your mood together.' },
        work:{ ko:'오래 키워온 것이 여물었는지가 관건입니다.', en:'The question is whether what you grew has ripened.' },
        money:{ ko:'들어오는 것과 쓰는 것이 같이 늘고 있는지 보면 좋습니다.', en:'Check whether what comes in and what goes out are rising together.' },
        rel:{ ko:'누가 누구를 돌보고 있는지가 핵심입니다.', en:'The heart of it is who is caring for whom.' } } },
  { id:'major-04', arcana:'major', num:4,
    name:{ ko:'황제', en:'The Emperor' },
    k:{ ko:['질서','권위','책임','구조'], en:['Order','Authority','Responsibility','Structure'] },
    u:{ ko:'규칙과 틀을 세울 때입니다. 흔들리지 않는 기준을 만들면 나머지가 따라옵니다. 책임을 지는 자리가 곧 힘이 되는 시기예요.', en:'Time to set rules and a frame. Build a standard that will not move and the rest follows. Carrying the responsibility is where the power is.' },
    r:{ ko:'경직된 통제이거나 무책임입니다. 고집이 상황을 굳게 만들거나, 기대야 할 권위가 부재한 상태일 수 있습니다.', en:'Rigid control, or none at all. Stubbornness is hardening the situation, or the authority you need is absent.' },
    t:{ love:{ ko:'주도권이 어디에 있는지가 관건입니다. 서로의 몫을 정해두면 도움이 됩니다.', en:'Where the initiative sits is the question. Agreeing on each person\'s part helps.' },
        work:{ ko:'규칙과 직책의 문제입니다. 책임 범위를 분명히 해두면 좋습니다.', en:'This is about rules and titles. Make the scope of responsibility clear.' },
        money:{ ko:'계획과 관리가 핵심입니다. 기준을 세워두면 지켜집니다.', en:'Planning and management are the core. Set a standard and it holds.' },
        rel:{ ko:'손윗사람이나 결정권자와의 거리가 주제입니다.', en:'The theme is your distance from someone older or in charge.' } } },
  { id:'major-05', arcana:'major', num:5,
    name:{ ko:'교황', en:'The Hierophant' },
    k:{ ko:['전통','배움','제도','조언'], en:['Tradition','Learning','Institution','Counsel'] },
    u:{ ko:'검증된 방식과 스승이 도움이 됩니다. 혼자 발명하지 말고 이미 있는 길을 배우세요. 공식적인 절차나 약속이 힘을 갖는 때입니다.', en:'Proven methods and teachers help. Do not invent alone; learn the road that already exists. Formal steps and promises carry weight now.' },
    r:{ ko:'관습이 답답하게 느껴집니다. 남의 기준을 그대로 따를 이유가 없어요. 다만 규칙을 깨려면 그만한 대가를 각오해야 합니다.', en:'Convention feels stifling. There is no reason to follow someone else\'s standard. But breaking a rule costs what it costs.' },
    t:{ love:{ ko:'정식 절차와 주변의 시선이 걸립니다. 먼저 겪어본 사람의 말도 참고하면 도움이 됩니다.', en:'Formal steps and how others see it are in play. The word of someone who has been there is worth hearing.' },
        work:{ ko:'검증된 방식을 따를지 말지가 관건입니다.', en:'The question is whether to follow the proven method.' },
        money:{ ko:'정공법과 지름길 사이의 선택입니다. 제도권 밖은 한 번 더 확인하면 편합니다.', en:'This is the choice between the straight road and the shortcut. Verify anything outside the system twice.' },
        rel:{ ko:'주변의 인정이 이 관계에 얼마나 중요한지가 주제입니다.', en:'How much outside approval matters to this bond is the theme.' } } },
  { id:'major-06', arcana:'major', num:6,
    name:{ ko:'연인', en:'The Lovers' },
    k:{ ko:['선택','결합','가치관','끌림'], en:['Choice','Union','Values','Attraction'] },
    u:{ ko:'마음이 통하는 만남, 혹은 무엇을 더 사랑하는지 정해야 하는 갈림길입니다. 머리가 아니라 가치관으로 고르라는 카드예요.', en:'A meeting where minds match, or a fork where you must name what you love more. Choose by values, not by arithmetic.' },
    r:{ ko:'어긋난 합, 미루는 결정입니다. 둘 다 갖겠다는 태도가 관계를 흐리고 있어요. 유혹과 진심을 구분해야 합니다.', en:'A mismatched pairing, a decision postponed. Wanting both is muddying it. Separate temptation from what is real.' },
    t:{ love:{ ko:'무엇을 더 아끼는지가 관건입니다. 조건이 아니라 가치로 보면 도움이 됩니다.', en:'What you value more is the question. Look at values rather than conditions.' },
        work:{ ko:'함께할 사람과 갈 길의 선택입니다. 둘 다 쥐려 하지 않으면 좋습니다.', en:'It is a choice of who to work with and which road. Try not to hold both.' },
        money:{ ko:'나눌지 몰아줄지가 핵심입니다. 하나를 고르는 편이 편합니다.', en:'Split or commit is the core. Picking one is usually easier.' },
        rel:{ ko:'맞는 사람과 아닌 사람을 가르는 자리입니다.', en:'This is the point where the right people and the wrong ones separate.' } } },
  { id:'major-07', arcana:'major', num:7,
    name:{ ko:'전차', en:'The Chariot' },
    k:{ ko:['추진','승리','통제','전진'], en:['Drive','Victory','Control','Advance'] },
    u:{ ko:'상반된 힘을 붙잡고 앞으로 나아갑니다. 의지로 밀어붙이면 결과가 나오는 국면이에요. 방향만 확실하면 속도는 문제가 안 됩니다.', en:'You hold two opposing forces and move anyway. Will produces results in this phase. If the direction is sure, speed is not the problem.' },
    r:{ ko:'고삐가 풀렸습니다. 방향 없는 질주이거나 제자리걸음이에요. 이기려는 마음이 정작 목적을 지워버리지 않았는지 보세요.', en:'The reins are loose. Either a run with no direction, or no movement at all. Check whether wanting to win erased the purpose.' },
    t:{ love:{ ko:'밀고 나가는 힘과 방향이 관건입니다. 상대의 속도를 함께 보면 도움이 됩니다.', en:'Force and direction are what matter. Watch the other person\'s pace alongside your own.' },
        work:{ ko:'추진력의 문제입니다. 방향이 맞는지만 한 번 더 확인하면 좋습니다.', en:'This is about momentum. Confirm the direction once more.' },
        money:{ ko:'적극성이 결과를 가릅니다. 목적지를 정해두면 편합니다.', en:'Being active decides the result. Fix the destination first.' },
        rel:{ ko:'내가 끌고 가는 관계인지가 주제입니다.', en:'The theme is whether you are the one pulling this along.' } } },
  { id:'major-08', arcana:'major', num:8,
    name:{ ko:'힘', en:'Strength' },
    k:{ ko:['용기','인내','부드러움','자제'], en:['Courage','Patience','Gentleness','Restraint'] },
    u:{ ko:'힘으로 누르는 대신 다독여 이깁니다. 두려움이나 욕망을 적으로 두지 않고 길들이는 태도가 통해요. 조용한 용기의 카드입니다.', en:'You win by soothing rather than by force. Treating fear or desire as something to tame instead of defeat works here. This is quiet courage.' },
    r:{ ko:'자신감이 바닥나거나 감정에 끌려다닙니다. 억지로 참는 것과 다스리는 것은 다릅니다. 먼저 스스로에게 너그러워지세요.', en:'Confidence is spent, or feeling is running you. Enduring and mastering are not the same. Start by being gentler with yourself.' },
    t:{ love:{ ko:'힘으로 누를지 다독일지가 관건입니다. 재촉하지 않으면 도움이 됩니다.', en:'Force or patience is the question. Not pressing helps.' },
        work:{ ko:'버티는 힘의 문제입니다. 조급함을 덜어내면 좋습니다.', en:'This is about staying power. Take the hurry out of it.' },
        money:{ ko:'조급하게 움직일지 두고 볼지가 핵심입니다.', en:'Move now or wait is the core.' },
        rel:{ ko:'감정을 누르고 있는지 다스리고 있는지 보면 좋습니다.', en:'Look at whether you are suppressing feeling or steadying it.' } } },
  { id:'major-09', arcana:'major', num:9,
    name:{ ko:'은둔자', en:'The Hermit' },
    k:{ ko:['성찰','고독','탐구','거리두기'], en:['Reflection','Solitude','Search','Distance'] },
    u:{ ko:'물러나서 생각을 정리할 시간입니다. 답을 남에게 묻기 전에 혼자 있어야 보이는 것이 있어요. 이 고독은 도피가 아니라 준비입니다.', en:'Time to step back and sort your thoughts. Something only becomes visible alone, before you ask anyone. This solitude is preparation, not escape.' },
    r:{ ko:'고립이 길어지고 있습니다. 문을 닫아걸다 외로움만 남았거나, 반대로 혼자 있을 틈이 없어 지쳤을 수 있어요.', en:'The isolation has run long. You shut the door and were left with loneliness, or you have had no time alone at all.' },
    t:{ love:{ ko:'혼자 있는 시간이 주제입니다. 답을 밖에서 찾고 있지 않은지 보면 도움이 됩니다.', en:'Time alone is the theme. Check whether you are looking for the answer outside.' },
        work:{ ko:'조용히 쌓는 시기인지가 관건입니다.', en:'The question is whether this is a season for building quietly.' },
        money:{ ko:'벌일 때인지 점검할 때인지의 문제입니다.', en:'Start something, or audit what you already have.' },
        rel:{ ko:'거리두기가 회복인지 도피인지 보면 좋습니다.', en:'Look at whether the distance is recovery or avoidance.' } } },
  { id:'major-10', arcana:'major', num:10,
    name:{ ko:'운명의 수레바퀴', en:'Wheel of Fortune' },
    k:{ ko:['전환','흐름','기회','주기'], en:['Turning','Flow','Opportunity','Cycle'] },
    u:{ ko:'상황이 저절로 움직입니다. 노력과 무관한 변화가 찾아오니 흐름에 올라타세요. 오래 막혔던 것이 풀리는 타이밍입니다.', en:'The situation moves on its own. Change arrives regardless of effort, so ride it. Long-stuck things loosen now.' },
    r:{ ko:'흐름이 불리하게 돌거나 같은 패턴이 반복됩니다. 통제할 수 없는 일에 힘을 쓰기보다 버틸 준비를 하세요.', en:'The turn is unfavourable, or the same pattern repeats. Rather than spending force on what you cannot control, prepare to hold on.' },
    t:{ love:{ ko:'내 뜻과 무관한 흐름이 관건입니다. 붙들 것과 놓을 것을 가르면 도움이 됩니다.', en:'What is moving without your say is the point. Sort what to hold from what to release.' },
        work:{ ko:'상황이 저절로 움직이는 국면입니다. 흐름을 거스르지 않으면 좋습니다.', en:'The situation moves by itself. Not fighting the current helps.' },
        money:{ ko:'타이밍이 결과를 가릅니다. 무리해서 붙들지 않으면 편합니다.', en:'Timing decides the outcome. Try not to hold on by force.' },
        rel:{ ko:'오고 가는 인연의 주기가 주제입니다.', en:'The theme is the cycle of people arriving and leaving.' } } },
  { id:'major-11', arcana:'major', num:11,
    name:{ ko:'정의', en:'Justice' },
    k:{ ko:['균형','책임','계약','인과'], en:['Balance','Accountability','Contract','Cause'] },
    u:{ ko:'뿌린 대로 거둡니다. 감정을 빼고 사실만 놓고 판단해야 할 때예요. 계약이나 법률, 공정한 결론과 인연이 깊은 카드입니다.', en:'You reap what you sowed. Judge on facts with the feeling taken out. This card sits close to contracts, law, and fair conclusions.' },
    r:{ ko:'한쪽으로 기운 저울입니다. 편견, 책임 회피, 불공정한 대우가 있어요. 자신의 몫도 정직하게 따져봐야 합니다.', en:'The scale tilts. There is bias, dodged responsibility, or unfair treatment. Be honest about your own share as well.' },
    t:{ love:{ ko:'주고받는 것이 한쪽으로 기울지 않았는지가 관건입니다.', en:'Whether give and take has tipped is the question.' },
        work:{ ko:'평가와 계약의 문제입니다. 기준이 무엇인지 확인하면 도움이 됩니다.', en:'This is about assessment and contracts. Confirm what the standard is.' },
        money:{ ko:'셈이 분명한지가 핵심입니다. 서류를 챙겨두면 편합니다.', en:'Clear accounting is the core. Keep the paperwork.' },
        rel:{ ko:'잘잘못을 어디까지 따질지가 주제입니다.', en:'How far to press right and wrong is the theme.' } } },
  { id:'major-12', arcana:'major', num:12,
    name:{ ko:'매달린 사람', en:'The Hanged Man' },
    k:{ ko:['정지','전환된 시각','희생','기다림'], en:['Suspension','Reversed view','Sacrifice','Waiting'] },
    u:{ ko:'멈춰 있는 것처럼 보이지만 관점이 뒤집히는 중입니다. 지금은 밀어붙일 때가 아니라 놓아줄 때예요. 기다림 자체가 행동입니다.', en:'It looks stopped, but the angle is turning over. This is not the moment to push; it is the moment to let go. Waiting is the action.' },
    r:{ ko:'무의미한 지연이자 헛된 희생입니다. 붙들고 있는 것을 놓지 못해 시간을 잃고 있어요. 순교자 역할을 그만둘 때입니다.', en:'Pointless delay and wasted sacrifice. You cannot release what you are holding, and time is going. Time to stop playing the martyr.' },
    t:{ love:{ ko:'멈춰 있는 시간을 어떻게 볼 것인가가 관건입니다. 억지로 밀지 않으면 도움이 됩니다.', en:'How you read the pause is the question. Not forcing it helps.' },
        work:{ ko:'진행이 아니라 관점의 문제입니다.', en:'This is about perspective, not progress.' },
        money:{ ko:'묶인 돈을 어떻게 볼지가 핵심입니다. 무리해서 빼지 않으면 편합니다.', en:'How you regard tied-up money is the core. Try not to pull it out by force.' },
        rel:{ ko:'한쪽만 참고 있지 않은지 보면 좋습니다.', en:'Look at whether only one side is enduring.' } } },
  { id:'major-13', arcana:'major', num:13,
    name:{ ko:'죽음', en:'Death' },
    k:{ ko:['종결','변형','정리','재탄생'], en:['Ending','Transformation','Clearing','Rebirth'] },
    u:{ ko:'끝나야 할 것이 끝납니다. 무서운 카드가 아니라 청산의 카드예요. 미련을 정리하면 곧바로 다음 국면이 열립니다.', en:'What must end, ends. Not a frightening card but a clearing one. Settle the attachment and the next phase opens at once.' },
    r:{ ko:'끝을 인정하지 못해 질질 끌고 있습니다. 변화에 대한 저항이 고통을 늘리는 중이에요. 놓아주는 연습이 필요합니다.', en:'You cannot admit the end and are dragging it out. Resistance to change is adding to the pain. Practise letting go.' },
    t:{ love:{ ko:'끝내야 할 것이 무엇인지가 관건입니다. 미련을 정리하면 도움이 됩니다.', en:'What needs to end is the question. Settling the attachment helps.' },
        work:{ ko:'정리하고 넘어갈 때인지의 문제입니다.', en:'Whether it is time to close and move on.' },
        money:{ ko:'청산해야 할 계정이나 빚이 핵심입니다. 미루지 않으면 편합니다.', en:'An account or a debt to settle is the core. Not postponing helps.' },
        rel:{ ko:'한 번 갈리는 인연이 주제입니다.', en:'A bond that parts once is the theme.' } } },
  { id:'major-14', arcana:'major', num:14,
    name:{ ko:'절제', en:'Temperance' },
    k:{ ko:['조화','중용','인내','치유'], en:['Harmony','Moderation','Patience','Healing'] },
    u:{ ko:'서로 다른 것을 알맞게 섞어 새로운 것을 만듭니다. 극단을 피하고 속도를 조절하면 자연스럽게 회복돼요. 시간이 약인 카드입니다.', en:'You blend unlike things in the right measure and make something new. Avoid extremes, control the pace, and recovery comes on its own. Time is the medicine.' },
    r:{ ko:'균형이 무너졌습니다. 과하거나 모자라거나, 성급해서 다 망칠 수 있어요. 조율할 지점을 다시 찾으세요.', en:'The balance is gone. Too much, too little, or too fast to survive. Find the point to adjust again.' },
    t:{ love:{ ko:'서로 다른 속도를 어떻게 맞출지가 관건입니다. 극단을 피하면 도움이 됩니다.', en:'How to match different speeds is the question. Avoiding extremes helps.' },
        work:{ ko:'여러 일의 배합이 문제입니다. 무리한 속도를 덜어내면 좋습니다.', en:'This is about the mix of several things. Take the excess speed out.' },
        money:{ ko:'수입과 지출의 균형이 핵심입니다. 비율을 다시 잡아보면 편합니다.', en:'Balance of income and outgo is the core. Reset the ratio.' },
        rel:{ ko:'중간에서 조율하는 자리가 주제입니다.', en:'The theme is the role of adjusting from the middle.' } } },
  { id:'major-15', arcana:'major', num:15,
    name:{ ko:'악마', en:'The Devil' },
    k:{ ko:['집착','속박','욕망','중독'], en:['Attachment','Bondage','Desire','Compulsion'] },
    u:{ ko:'끊어야 하는 줄 알면서도 붙잡고 있는 것이 있습니다. 사슬은 느슨하며, 묶여 있기로 선택한 쪽은 자신이에요. 욕망 자체가 아니라 종속이 문제입니다.', en:'You are holding something you know you should cut. The chain is loose, and you are the one who chose to stay bound. The problem is not desire but dependence.' },
    r:{ ko:'속박에서 벗어나기 시작합니다. 무엇에 매여 있었는지 자각하는 단계예요. 다만 되돌아가기도 쉬우니 방심하지 마세요.', en:'The binding is starting to give. You are seeing what held you. It is easy to go back, so stay awake.' },
    t:{ love:{ ko:'무엇에 매여 있는지가 관건입니다. 사슬을 쥔 손이 누구인지 보면 도움이 됩니다.', en:'What you are bound to is the question. Look at whose hand holds the chain.' },
        work:{ ko:'조건에 묶여 있는지가 문제입니다.', en:'Whether conditions have you tied.' },
        money:{ ko:'빚과 소비 습관이 핵심입니다. 새는 곳을 적어보면 편합니다.', en:'Debt and spending habits are the core. Write down where it leaks.' },
        rel:{ ko:'서로를 갉아먹고 있지 않은지 보면 좋습니다.', en:'Look at whether you are wearing each other down.' } } },
  { id:'major-16', arcana:'major', num:16,
    name:{ ko:'탑', en:'The Tower' },
    k:{ ko:['붕괴','충격','폭로','해방'], en:['Collapse','Shock','Exposure','Release'] },
    u:{ ko:'모래 위에 지은 것이 무너집니다. 갑작스럽고 아프지만, 거짓 위에 세운 구조라 결국 무너질 것이었어요. 무너진 뒤가 훨씬 단단합니다.', en:'What was built on sand comes down. Sudden and painful, but it stood on something false and would have fallen anyway. What follows is far more solid.' },
    r:{ ko:'붕괴를 간신히 미루고 있거나 이미 겪은 충격을 수습하는 중입니다. 버티는 비용이 무너지는 비용보다 클 수 있어요.', en:'You are barely postponing the collapse, or clearing up after a shock already taken. Holding on may cost more than falling.' },
    t:{ love:{ ko:'무너질 것이 무너지는 자리입니다. 무엇이 모래 위에 있었는지 보면 도움이 됩니다.', en:'This is where what should fall falls. Look at what was standing on sand.' },
        work:{ ko:'조직이나 자리의 흔들림이 관건입니다. 대비를 해두면 좋습니다.', en:'A shake in the role or the organisation. Preparing helps.' },
        money:{ ko:'예기치 못한 지출이 핵심입니다. 여유분을 남겨두면 편합니다.', en:'An unplanned expense is the core. Keep a reserve.' },
        rel:{ ko:'한 번에 갈릴 수 있는 관계가 주제입니다.', en:'A bond that could break all at once is the theme.' } } },
  { id:'major-17', arcana:'major', num:17,
    name:{ ko:'별', en:'The Star' },
    k:{ ko:['희망','회복','영감','신뢰'], en:['Hope','Recovery','Inspiration','Trust'] },
    u:{ ko:'폭풍이 지나간 자리에 조용한 빛이 듭니다. 서두르지 않아도 회복되고, 진심이 통하는 시기예요. 다시 믿어봐도 좋습니다.', en:'Quiet light falls where the storm passed. You heal without hurrying, and sincerity carries. It is alright to believe again.' },
    r:{ ko:'희망을 잃고 냉소가 자리 잡았습니다. 자신에 대한 믿음이 흔들리는 중이에요. 작은 것부터 다시 쌓아야 합니다.', en:'Hope is gone and cynicism moved in. Faith in yourself is shaky. Build again from something small.' },
    t:{ love:{ ko:'다시 믿을 수 있는가가 관건입니다. 서두르지 않으면 도움이 됩니다.', en:'Whether you can trust again is the question. Not rushing helps.' },
        work:{ ko:'조용한 회복의 시기인지가 문제입니다.', en:'Whether this is a season of quiet recovery.' },
        money:{ ko:'서서히 돌아오는 흐름이 핵심입니다. 작은 것부터 쌓으면 편합니다.', en:'A slow return is the core. Stack small things first.' },
        rel:{ ko:'진심이 통하는 사람이 누구인지가 주제입니다.', en:'Who the sincerity reaches is the theme.' } } },
  { id:'major-18', arcana:'major', num:18,
    name:{ ko:'달', en:'The Moon' },
    k:{ ko:['불안','착각','무의식','모호함'], en:['Anxiety','Illusion','The unconscious','Uncertainty'] },
    u:{ ko:'보이는 것이 전부가 아닙니다. 불안이 사실을 왜곡하고 있으니 결론을 미루세요. 꿈과 직감이 단서를 주는 시기입니다.', en:'What you see is not all of it. Anxiety is bending the facts, so hold the conclusion. Dreams and instinct hand you clues now.' },
    r:{ ko:'안개가 걷힙니다. 오해가 풀리고 두려움의 실체가 드러나요. 다만 아직 밝히지 못한 것이 남아 있을 수 있습니다.', en:'The fog lifts. Misunderstandings clear and fear shows its actual size. Something may still be unlit.' },
    t:{ love:{ ko:'보이는 것이 전부가 아닐 수 있습니다. 결론을 미뤄두면 도움이 됩니다.', en:'What is visible may not be all of it. Holding the conclusion helps.' },
        work:{ ko:'정보의 불투명함이 관건입니다. 확인되지 않은 말은 걸러두면 좋습니다.', en:'Murky information is the issue. Filter out what is unverified.' },
        money:{ ko:'숫자와 실제가 다를 수 있습니다. 직접 확인하면 편합니다.', en:'The numbers and the reality may differ. Check them yourself.' },
        rel:{ ko:'겉과 속이 다른 사람이 있는지가 주제입니다.', en:'Whether someone\'s outside and inside differ is the theme.' } } },
  { id:'major-19', arcana:'major', num:19,
    name:{ ko:'태양', en:'The Sun' },
    k:{ ko:['성공','활력','명료함','기쁨'], en:['Success','Vitality','Clarity','Joy'] },
    u:{ ko:'숨길 것 없이 환한 상태입니다. 하는 일이 잘 풀리고 관계도 투명해져요. 있는 그대로의 자신으로 인정받는 시기입니다.', en:'Bright, with nothing to hide. Work goes well and bonds turn transparent. You are recognised as you actually are.' },
    r:{ ko:'기쁨이 흐려졌거나 지연됩니다. 잘 되고 있는데도 즐기지 못하거나, 과한 낙관이 현실을 가릴 수 있어요.', en:'The joy is dimmed or delayed. You cannot enjoy what is going well, or optimism is covering the facts.' },
    t:{ love:{ ko:'숨길 것 없이 드러나는 관계인가가 관건입니다.', en:'Whether this is a bond with nothing to hide.' },
        work:{ ko:'드러내고 인정받는 국면입니다. 알릴 것은 알리면 도움이 됩니다.', en:'A phase of showing and being recognised. Say what is worth saying.' },
        money:{ ko:'벌이와 씀씀이가 함께 커집니다. 기쁨에 취하지 않으면 편합니다.', en:'Earning and spending grow together. Try not to get carried away.' },
        rel:{ ko:'함께 있으면 기운이 나는 사람이 누구인지가 주제입니다.', en:'Who leaves you with more energy is the theme.' } } },
  { id:'major-20', arcana:'major', num:20,
    name:{ ko:'심판', en:'Judgement' },
    k:{ ko:['각성','결산','부름','용서'], en:['Awakening','Reckoning','Calling','Forgiveness'] },
    u:{ ko:'지나온 것을 결산하고 새 국면으로 부름을 받습니다. 오래된 문제를 정면으로 마주할 때예요. 용서, 특히 자신에 대한 용서가 열쇠입니다.', en:'You settle what has passed and are called into a new phase. Time to face an old problem directly. Forgiveness, of yourself above all, is the key.' },
    r:{ ko:'부름을 못 들은 척하고 있습니다. 과거에 대한 자책이 발목을 잡거나, 판단을 계속 미루는 중이에요.', en:'You are pretending not to hear the call. Self-blame has your ankle, or you keep deferring the verdict.' },
    t:{ love:{ ko:'지난 인연을 어떻게 매듭지을지가 관건입니다. 자신을 탓하지 않으면 도움이 됩니다.', en:'How to close an old bond is the question. Not blaming yourself helps.' },
        work:{ ko:'지나온 것의 결산이 문제입니다.', en:'The reckoning of everything that came before.' },
        money:{ ko:'오래된 셈이 핵심입니다. 미뤄둔 것부터 보면 편합니다.', en:'An old account is the core. Start with what you postponed.' },
        rel:{ ko:'용서할지 말지가 주제입니다.', en:'Whether to forgive is the theme.' } } },
  { id:'major-21', arcana:'major', num:21,
    name:{ ko:'세계', en:'The World' },
    k:{ ko:['완성','통합','성취','졸업'], en:['Completion','Integration','Achievement','Graduation'] },
    u:{ ko:'한 사이클이 온전히 닫힙니다. 애쓴 것이 형태를 갖추고 다음 무대로 넘어가요. 충분히 잘했다고 말해도 되는 자리입니다.', en:'One cycle closes fully. What you worked at takes shape and moves to the next stage. You are allowed to say it was enough.' },
    r:{ ko:'거의 다 왔는데 마무리가 안 됩니다. 미련이나 미완의 과제가 남아 있어요. 끝을 선언해야 다음이 시작됩니다.', en:'Nearly there and it will not finish. An attachment or an unfinished task remains. Declare the end and the next thing starts.' },
    t:{ love:{ ko:'한 국면이 닫히는 자리입니다. 끝을 인정해야 다음이 열립니다.', en:'A phase that closes. Admitting the end opens the next.' },
        work:{ ko:'마무리와 다음 무대가 관건입니다.', en:'Finishing, and the stage after it.' },
        money:{ ko:'목표한 금액에 닿는 지점입니다. 다음 계획을 세워두면 편합니다.', en:'The point where you reach the figure. Plan what comes after.' },
        rel:{ ko:'오래 이어질 사람이 누구인지가 주제입니다.', en:'Who stays for the long run is the theme.' } } },

  // ── 완드 (불 / 열정·행동) ──
  { id:'wands-01', arcana:'minor', num:1, suit:'wands',
    name:{ ko:'완드 에이스', en:'Ace of Wands' },
    k:{ ko:['영감','출발','불씨'], en:['Spark','Start','Impulse'] },
    u:{ ko:'하고 싶은 것이 생겼습니다. 아직 형태는 없지만 에너지가 확실해요. 망설이면 꺼지는 종류의 불씨입니다.', en:'You have found something you want to do. It has no shape yet but the energy is real. This is the kind of spark that goes out if you hesitate.' },
    r:{ ko:'의욕이 헛돕니다. 시작할 명분이 없거나 타이밍이 이릅니다.', en:'The drive is spinning without traction. Either there is no reason to begin or the timing is early.' },
    t:{ love:{ ko:'불씨가 붙었는지가 관건입니다. 망설이는 사이 식지 않는지 보면 도움이 됩니다.', en:'Whether the spark caught is the question. Watch that it does not cool while you hesitate.' },
        work:{ ko:'하고 싶은 마음이 있는지가 문제입니다. 형태가 없어도 적어두면 좋습니다.', en:'Whether you actually want it is the issue. Write it down even without a shape.' },
        money:{ ko:'새 벌이의 실마리가 핵심입니다.', en:'A thread toward new income is the core.' },
        rel:{ ko:'먼저 연락할 것인가가 주제입니다.', en:'Whether you reach out first is the theme.' } } },
  { id:'wands-02', arcana:'minor', num:2, suit:'wands',
    name:{ ko:'완드 2', en:'Two of Wands' },
    k:{ ko:['계획','전망','선택'], en:['Planning','Outlook','Choice'] },
    u:{ ko:'손에 쥔 것을 확인하고 더 넓은 곳을 내다봅니다. 구상은 끝났고 범위를 정할 차례예요.', en:'You take stock of what is in hand and look further out. The conceiving is done; now you set the scope.' },
    r:{ ko:'계획만 세우다 시간이 갑니다. 안전한 자리에 머무를지 나갈지 결정하지 못하는 중입니다.', en:'Time goes while you keep planning. You cannot decide whether to stay somewhere safe or leave.' },
    t:{ love:{ ko:'이 관계를 어디까지 끌고 갈지가 관건입니다.', en:'How far you intend to take this is what matters.' },
        work:{ ko:'구상과 범위의 문제입니다. 다 하려 들지 않으면 도움이 됩니다.', en:'Concept and scope are the issue. Not trying to do all of it helps.' },
        money:{ ko:'굴릴 곳의 선택이 핵심입니다. 넓게 살펴보면 좋습니다.', en:'Choosing where to put it is the core. Look widely first.' },
        rel:{ ko:'곁에 둘 사람을 가늠하는 자리입니다.', en:'This is the point of gauging who to keep close.' } } },
  { id:'wands-03', arcana:'minor', num:3, suit:'wands',
    name:{ ko:'완드 3', en:'Three of Wands' },
    k:{ ko:['확장','기다림','전개'], en:['Expansion','Waiting','Unfolding'] },
    u:{ ko:'배는 이미 떠났고 결과가 오는 중입니다. 시야를 넓히면 협업이나 외부와의 인연이 생깁니다.', en:'The ship has sailed and the result is on its way. Widen the view and partners or distant contacts appear.' },
    r:{ ko:'기다리던 소식이 늦어지거나 계획이 좁습니다. 예상이 빗나갈 수 있어요.', en:'The news you waited for is late, or the plan is too narrow. Expectations may be off.' },
    t:{ love:{ ko:'보낸 마음의 답을 기다리는 시간이 주제입니다.', en:'The waiting for an answer you sent is the theme.' },
        work:{ ko:'벌여둔 일의 결과가 오는 중입니다. 재촉하지 않으면 도움이 됩니다.', en:'What you set going is on its way back. Not hurrying it helps.' },
        money:{ ko:'넣어둔 것이 자라는 시간이 핵심입니다.', en:'The time it takes for what you planted to grow is the core.' },
        rel:{ ko:'멀리 있는 사람과의 거리가 관건입니다.', en:'Distance with someone far away is what matters.' } } },
  { id:'wands-04', arcana:'minor', num:4, suit:'wands',
    name:{ ko:'완드 4', en:'Four of Wands' },
    k:{ ko:['축하','안정','귀속'], en:['Celebration','Stability','Belonging'] },
    u:{ ko:'한 단계를 마치고 함께 기뻐하는 자리입니다. 집, 가족, 소속이 든든해지는 시기예요.', en:'You finish a stage and take joy in it together. Home, family and belonging grow solid.' },
    r:{ ko:'축하가 미뤄지거나 소속감이 흔들립니다. 겉으로만 화목한 상태일 수 있어요.', en:'The celebration is delayed, or belonging is unsteady. It may be harmony only on the surface.' },
    t:{ love:{ ko:'함께 자리를 잡을 수 있는가가 관건입니다.', en:'Whether you can settle somewhere together is the question.' },
        work:{ ko:'한 단계를 마친 자리의 안정이 주제입니다.', en:'The steadiness of a place after one stage closes.' },
        money:{ ko:'집과 살림에 들어가는 돈이 핵심입니다. 기반이 되는지 보면 좋습니다.', en:'Money goes to home and living. Look at whether it becomes a foundation.' },
        rel:{ ko:'속한 무리에서의 편안함이 문제입니다.', en:'Ease inside the group you belong to is the issue.' } } },
  { id:'wands-05', arcana:'minor', num:5, suit:'wands',
    name:{ ko:'완드 5', en:'Five of Wands' },
    k:{ ko:['경쟁','충돌','소란'], en:['Competition','Clash','Noise'] },
    u:{ ko:'서로 다른 목소리가 부딪칩니다. 악의보다는 혈기의 문제이고, 겨루는 과정에서 실력이 붙어요.', en:'Different voices collide. It is hot blood rather than malice, and skill sharpens in the contest.' },
    r:{ ko:'싸움을 피하느라 문제가 곪습니다. 혹은 소모적인 다툼이 끝나갑니다.', en:'Avoiding the fight lets the problem fester. Or a draining quarrel is ending.' },
    t:{ love:{ ko:'끼어드는 사람이나 잦은 다툼이 관건입니다.', en:'Someone cutting in, or frequent small quarrels.' },
        work:{ ko:'같은 자리를 두고 겨루는 국면입니다. 실력으로 겨루면 남는 것이 있습니다.', en:'A contest for the same seat. Competing on merit leaves something behind.' },
        money:{ ko:'돈을 둘러싼 말이 핵심입니다.', en:'Words around money are the core.' },
        rel:{ ko:'기 싸움에 악의가 있는지 보면 도움이 됩니다.', en:'Look at whether there is malice under the friction.' } } },
  { id:'wands-06', arcana:'minor', num:6, suit:'wands',
    name:{ ko:'완드 6', en:'Six of Wands' },
    k:{ ko:['승리','인정','자신감'], en:['Victory','Recognition','Confidence'] },
    u:{ ko:'노력이 눈에 보이게 인정받습니다. 드러내도 좋은 시기이니 성과를 알리세요.', en:'The work is recognised visibly. This is a season for showing, so let people know.' },
    r:{ ko:'인정받지 못하거나 자만이 발목을 잡습니다. 평가에 지나치게 매여 있을 수도 있어요.', en:'You go unrecognised, or self-regard trips you. You may also be too tied to the verdict.' },
    t:{ love:{ ko:'마음이 받아들여지는가가 관건입니다.', en:'Whether the feeling is received is the question.' },
        work:{ ko:'성과를 드러낼 때인지가 문제입니다. 알릴 것은 알리면 도움이 됩니다.', en:'Whether it is time to show the result. Saying what is worth saying helps.' },
        money:{ ko:'애쓴 만큼 돌아오는지가 핵심입니다.', en:'Whether the effort comes back is the core.' },
        rel:{ ko:'무리 안에서의 자리가 주제입니다.', en:'Your standing inside the group is the theme.' } } },
  { id:'wands-07', arcana:'minor', num:7, suit:'wands',
    name:{ ko:'완드 7', en:'Seven of Wands' },
    k:{ ko:['방어','고수','버티기'], en:['Defence','Holding','Endurance'] },
    u:{ ko:'지켜야 할 자리가 있고 도전이 들어옵니다. 유리한 위치에 있으니 물러서지 마세요.', en:'There is ground to hold and a challenge to it. You have the higher position, so do not step back.' },
    r:{ ko:'혼자 다 막으려다 지쳤습니다. 지킬 가치가 있는지 다시 따져볼 때입니다.', en:'You are worn out from blocking alone. Time to reconsider whether it is worth defending.' },
    t:{ love:{ ko:'지켜야 할 관계에 끼어드는 사람이 관건입니다.', en:'Someone stepping into a bond you want to keep.' },
        work:{ ko:'자리를 지키는 싸움입니다. 물러설 지점을 정해두면 좋습니다.', en:'A fight to hold your ground. Decide in advance where you would yield.' },
        money:{ ko:'지금 가진 것을 지키는 문제입니다.', en:'This is about protecting what you already have.' },
        rel:{ ko:'내 편이 누구인지 분명히 해두면 도움이 됩니다.', en:'Making clear who is on your side helps.' } } },
  { id:'wands-08', arcana:'minor', num:8, suit:'wands',
    name:{ ko:'완드 8', en:'Eight of Wands' },
    k:{ ko:['속도','소식','급전개'], en:['Speed','News','Rush'] },
    u:{ ko:'모든 것이 빠르게 움직입니다. 연락, 이동, 진행이 한꺼번에 몰려와요. 지금 보내야 할 메시지가 있습니다.', en:'Everything moves fast. Messages, travel and progress arrive at once. There is something you should send now.' },
    r:{ ko:'일이 지연되거나 엇갈립니다. 성급한 연락이 오해를 만들 수 있어요.', en:'Things are delayed or crossing. A hasty message can create a misunderstanding.' },
    t:{ love:{ ko:'연락과 속도가 관건입니다.', en:'Contact and pace are what matter.' },
        work:{ ko:'한꺼번에 몰리는 일이 문제입니다. 순서를 정해두면 도움이 됩니다.', en:'Work arriving all at once. Setting an order helps.' },
        money:{ ko:'빨라지는 입출금이 핵심입니다.', en:'Money moving in and out quickly is the core.' },
        rel:{ ko:'여러 곳에서 오는 소식이 주제입니다.', en:'News from several directions is the theme.' } } },
  { id:'wands-09', arcana:'minor', num:9, suit:'wands',
    name:{ ko:'완드 9', en:'Nine of Wands' },
    k:{ ko:['끈기','경계','마지막 고비'], en:['Persistence','Guard','Last stretch'] },
    u:{ ko:'상처를 안고도 서 있습니다. 거의 다 왔으니 한 번만 더 버티면 됩니다.', en:'You are standing with the wounds still on you. You are nearly there; hold once more.' },
    r:{ ko:'경계심이 지나쳐 스스로를 고립시킵니다. 번아웃 직전이라면 멈추는 것이 맞아요.', en:'Wariness has gone far enough to isolate you. If you are at the edge of burnout, stopping is right.' },
    t:{ love:{ ko:'지난 상처가 마음을 막고 있는지가 관건입니다.', en:'Whether old hurt is blocking you is the question.' },
        work:{ ko:'마지막 고비입니다. 한 번 더 버틸 힘이 있는지 보면 도움이 됩니다.', en:'The last stretch. Look at whether you have one more push in you.' },
        money:{ ko:'조금 더 아낄 여지가 있는지가 핵심입니다.', en:'Whether there is room to tighten a little more.' },
        rel:{ ko:'경계심이 사람을 밀어내고 있지 않은지 보면 좋습니다.', en:'Look at whether your guard is pushing people away.' } } },
  { id:'wands-10', arcana:'minor', num:10, suit:'wands',
    name:{ ko:'완드 10', en:'Ten of Wands' },
    k:{ ko:['과부하','책임','짐'], en:['Overload','Duty','Burden'] },
    u:{ ko:'너무 많이 짊어졌습니다. 목표는 가깝지만 이대로는 도착 전에 무너져요. 내려놓을 것을 고르세요.', en:'You are carrying too much. The goal is close but at this rate you break before arriving. Choose what to put down.' },
    r:{ ko:'짐을 내려놓거나, 떠넘기고 있습니다. 혼자 다 하려던 태도를 바꾸는 중입니다.', en:'You are setting the load down, or handing it off. The habit of doing everything alone is changing.' },
    t:{ love:{ ko:'혼자 짊어지고 있지 않은지가 관건입니다.', en:'Whether you are carrying it alone.' },
        work:{ ko:'안은 일의 양이 문제입니다. 하나는 내려놓으면 도움이 됩니다.', en:'The volume you took on. Putting one thing down helps.' },
        money:{ ko:'갚을 것의 무게가 핵심입니다.', en:'The weight of what you owe is the core.' },
        rel:{ ko:'부탁을 다 받아주고 있지 않은지 보면 좋습니다.', en:'Look at whether you accept every request.' } } },
  { id:'wands-11', arcana:'minor', num:11, suit:'wands',
    name:{ ko:'완드 페이지', en:'Page of Wands' },
    k:{ ko:['호기심','신선함','시도'], en:['Curiosity','Freshness','Attempt'] },
    u:{ ko:'서툴러도 신나게 뛰어드는 에너지입니다. 새 소식이나 제안이 들어와요.', en:'Energy that dives in gladly even when clumsy. News or an offer arrives.' },
    r:{ ko:'금방 식는 열정입니다. 벌여놓고 수습을 못 하는 중일 수 있어요.', en:'Enthusiasm that cools quickly. You may be starting things you cannot finish.' },
    t:{ love:{ ko:'아직 가벼운 설렘이 주제입니다.', en:'A light flutter, still early.' },
        work:{ ko:'새 제안과 배울 기회가 관건입니다.', en:'A new offer or a chance to learn.' },
        money:{ ko:'작게 시험해볼 것인가가 문제입니다.', en:'Whether to try it in a small size.' },
        rel:{ ko:'새로 들어오는 사람이 핵심입니다.', en:'Someone new coming in is the core.' } } },
  { id:'wands-12', arcana:'minor', num:12, suit:'wands',
    name:{ ko:'완드 나이트', en:'Knight of Wands' },
    k:{ ko:['돌진','열정','모험'], en:['Charge','Passion','Adventure'] },
    u:{ ko:'거침없이 밀고 나갑니다. 매력적이고 빠르지만 뒷일은 생각하지 않는 방식이에요.', en:'You push ahead without flinching. Attractive and fast, but it does not think about afterwards.' },
    r:{ ko:'무모함이 사고를 부릅니다. 시작만 하고 떠나버리는 태도를 조심하세요.', en:'Recklessness invites accidents. Beware of starting and walking away.' },
    t:{ love:{ ko:'뜨겁지만 오래갈지가 관건입니다.', en:'Hot, but whether it lasts is the question.' },
        work:{ ko:'밀고 나가는 속도가 문제입니다. 마무리할 사람을 정해두면 도움이 됩니다.', en:'The speed of the push. Deciding who finishes helps.' },
        money:{ ko:'과감함과 무모함 사이입니다. 뒷일을 한 번 보면 편합니다.', en:'Between bold and reckless. Look once at the aftermath.' },
        rel:{ ko:'시끄럽고 재미있는 사람과의 거리가 주제입니다.', en:'Distance with someone loud and entertaining.' } } },
  { id:'wands-13', arcana:'minor', num:13, suit:'wands',
    name:{ ko:'완드 퀸', en:'Queen of Wands' },
    k:{ ko:['자신감','매력','주도'], en:['Confidence','Presence','Initiative'] },
    u:{ ko:'스스로를 잘 알고 당당합니다. 사람을 끌어당기고 분위기를 이끄는 힘이 있어요.', en:'You know yourself and stand square. There is a pull that gathers people and sets the mood.' },
    r:{ ko:'인정 욕구나 질투가 앞섭니다. 자신감이 허세로 바뀌지 않게 하세요.', en:'The need to be seen, or envy, comes first. Keep confidence from turning into display.' },
    t:{ love:{ ko:'끌어당기는 쪽이 나인지가 관건입니다.', en:'Whether you are the one drawing.' },
        work:{ ko:'사람을 모으는 힘이 주제입니다.', en:'The power to gather people is the theme.' },
        money:{ ko:'감이 맞는지가 핵심입니다. 자만하지 않으면 좋습니다.', en:'Whether your read is right. Not overrating it helps.' },
        rel:{ ko:'무리의 중심에 서는 자리입니다.', en:'The seat at the centre of the group.' } } },
  { id:'wands-14', arcana:'minor', num:14, suit:'wands',
    name:{ ko:'완드 킹', en:'King of Wands' },
    k:{ ko:['리더십','비전','결단'], en:['Leadership','Vision','Decision'] },
    u:{ ko:'큰 그림을 보고 사람을 움직입니다. 결정을 내리고 책임지는 자리에 어울려요.', en:'You see the whole picture and move people. This suits a seat where you decide and carry it.' },
    r:{ ko:'독선과 성급한 지시입니다. 권위를 앞세워 밀어붙이면 사람이 떠납니다.', en:'Self-will and hasty orders. Push with authority and people leave.' },
    t:{ love:{ ko:'이끄는 쪽과 따르는 쪽이 관건입니다.', en:'Who leads and who follows.' },
        work:{ ko:'결정과 책임의 자리입니다.', en:'The seat of deciding and carrying it.' },
        money:{ ko:'크게 볼 것인가가 문제입니다. 혼자 정하지 않으면 도움이 됩니다.', en:'Whether to think big. Not deciding alone helps.' },
        rel:{ ko:'사람을 움직이는 위치가 주제입니다.', en:'A position that moves people is the theme.' } } },

  // ── 컵 (물 / 감정·관계) ──
  { id:'cups-01', arcana:'minor', num:1, suit:'cups',
    name:{ ko:'컵 에이스', en:'Ace of Cups' },
    k:{ ko:['새 감정','열림','사랑'], en:['New feeling','Opening','Love'] },
    u:{ ko:'마음이 열립니다. 새로운 인연이나 감정이 흘러들어오는 시작점이에요.', en:'The heart opens. This is the starting point where a new bond or feeling flows in.' },
    r:{ ko:'감정을 닫아두고 있습니다. 표현하지 못한 마음이 고여 있어요.', en:'You are keeping feeling shut. Something unexpressed has pooled.' },
    t:{ love:{ ko:'마음을 열 것인가가 관건입니다. 재지 않으면 도움이 됩니다.', en:'Whether to open is the question. Not weighing it helps.' },
        work:{ ko:'애정이 가는 일인지가 문제입니다.', en:'Whether it is work you can care about.' },
        money:{ ko:'마음 가는 곳에 쓰는 돈이 핵심입니다.', en:'Money spent where the heart goes is the core.' },
        rel:{ ko:'마음을 나눌 사람이 있는지가 주제입니다.', en:'Whether there is someone to share it with.' } } },
  { id:'cups-02', arcana:'minor', num:2, suit:'cups',
    name:{ ko:'컵 2', en:'Two of Cups' },
    k:{ ko:['교감','약속','파트너십'], en:['Rapport','Promise','Partnership'] },
    u:{ ko:'서로를 알아보는 만남입니다. 일대일의 신뢰가 만들어지는 자리예요.', en:'A meeting where two recognise each other. Trust between two people is being made.' },
    r:{ ko:'균형이 깨진 관계입니다. 한쪽만 주고 있거나 오해가 쌓였어요.', en:'The balance is off. One side is giving, or misunderstanding has stacked up.' },
    t:{ love:{ ko:'서로를 알아보는 순간이 관건입니다.', en:'The moment of recognising each other.' },
        work:{ ko:'함께 일할 사람의 선택이 문제입니다.', en:'Choosing who to work with is the issue.' },
        money:{ ko:'동업과 공동 지출이 핵심입니다. 몫을 미리 적어두면 편합니다.', en:'Partnership and shared spending. Write the shares down first.' },
        rel:{ ko:'일대일의 신뢰가 주제입니다.', en:'One-to-one trust is the theme.' } } },
  { id:'cups-03', arcana:'minor', num:3, suit:'cups',
    name:{ ko:'컵 3', en:'Three of Cups' },
    k:{ ko:['우정','축하','공유'], en:['Friendship','Celebration','Sharing'] },
    u:{ ko:'함께 웃을 사람들이 있습니다. 모임, 재회, 기쁜 소식이 있는 시기예요.', en:'There are people to laugh with. A gathering, a reunion, good news.' },
    r:{ ko:'과한 어울림이 소모적입니다. 혹은 무리 안에서 겉도는 느낌이 들어요.', en:'Too much company is draining. Or you feel outside the circle you are in.' },
    t:{ love:{ ko:'주변에 알릴 만한 일인가가 관건입니다.', en:'Whether it is something to tell people about.' },
        work:{ ko:'팀으로 움직이는 것이 주제입니다.', en:'Moving as a team is the theme.' },
        money:{ ko:'모임과 선물에 나가는 돈이 핵심입니다. 한도를 정해두면 편합니다.', en:'Money going to gatherings and gifts. A limit helps.' },
        rel:{ ko:'모임과 재회가 문제입니다.', en:'Gatherings and reunions are the issue.' } } },
  { id:'cups-04', arcana:'minor', num:4, suit:'cups',
    name:{ ko:'컵 4', en:'Four of Cups' },
    k:{ ko:['권태','무관심','재고'], en:['Boredom','Indifference','Reconsider'] },
    u:{ ko:'가진 것에 시큰둥합니다. 눈앞에 내밀어진 기회를 못 보고 있을 수 있어요.', en:'You are lukewarm about what you have. You may not be seeing an offer held out in front of you.' },
    r:{ ko:'권태에서 빠져나옵니다. 다시 관심이 생기고 제안을 받아들일 마음이 들어요.', en:'You come out of the boredom. Interest returns and you are ready to accept.' },
    t:{ love:{ ko:'익숙함에 시큰둥해졌는지가 관건입니다. 눈앞의 마음을 한 번 보면 도움이 됩니다.', en:'Whether familiarity dulled it. Looking once at what is offered helps.' },
        work:{ ko:'하는 일의 의미가 문제입니다.', en:'The meaning of what you do is the issue.' },
        money:{ ko:'들어온 제안에 관심이 가는지가 핵심입니다.', en:'Whether the offer that came interests you.' },
        rel:{ ko:'만나도 심드렁한 이유가 주제입니다.', en:'Why meeting feels flat is the theme.' } } },
  { id:'cups-05', arcana:'minor', num:5, suit:'cups',
    name:{ ko:'컵 5', en:'Five of Cups' },
    k:{ ko:['상실','후회','애도'], en:['Loss','Regret','Grief'] },
    u:{ ko:'잃은 것에 시선이 묶여 있습니다. 뒤에 아직 남은 잔이 있다는 걸 보지 못하는 상태예요.', en:'Your eyes are fixed on what was lost. You cannot see the cups still standing behind you.' },
    r:{ ko:'슬픔을 지나 돌아섭니다. 용서와 회복이 시작됩니다.', en:'You pass through the grief and turn. Forgiveness and recovery begin.' },
    t:{ love:{ ko:'잃은 쪽만 보고 있지 않은지가 관건입니다. 남은 쪽도 보면 도움이 됩니다.', en:'Whether you are only looking at what is gone. Looking at what remains helps.' },
        work:{ ko:'놓친 기회를 되새기는 시간이 문제입니다.', en:'Time spent replaying a missed chance.' },
        money:{ ko:'손해 본 것에 묶인 마음이 핵심입니다.', en:'A mind tied to a loss is the core.' },
        rel:{ ko:'남아 있는 사람이 주제입니다.', en:'The people still here are the theme.' } } },
  { id:'cups-06', arcana:'minor', num:6, suit:'cups',
    name:{ ko:'컵 6', en:'Six of Cups' },
    k:{ ko:['추억','순수','재회'], en:['Memory','Innocence','Reunion'] },
    u:{ ko:'과거의 인연이나 익숙한 온기가 찾아옵니다. 순수한 호의를 주고받는 시기예요.', en:'An old bond or a familiar warmth comes round. A season of plain goodwill given and taken.' },
    r:{ ko:'추억에 갇혀 현재를 못 삽니다. 돌아갈 수 없는 것을 붙들고 있어요.', en:'You are caught in memory and missing the present. You are holding what cannot be returned to.' },
    t:{ love:{ ko:'옛사람과 옛 기억이 관건입니다.', en:'Old people and old memories.' },
        work:{ ko:'예전 일이나 옛 동료와의 인연이 문제입니다.', en:'Past work or former colleagues coming round again.' },
        money:{ ko:'오래된 것의 값이 핵심입니다.', en:'The value in something old is the core.' },
        rel:{ ko:'오랜 친구와의 거리가 주제입니다.', en:'Distance with a long-standing friend.' } } },
  { id:'cups-07', arcana:'minor', num:7, suit:'cups',
    name:{ ko:'컵 7', en:'Seven of Cups' },
    k:{ ko:['환상','선택지','혼란'], en:['Illusion','Options','Confusion'] },
    u:{ ko:'선택지가 너무 많고 대부분은 그럴듯한 그림입니다. 실체가 있는 것을 골라내세요.', en:'There are too many options and most are plausible pictures. Pick out the one with substance.' },
    r:{ ko:'현실 감각이 돌아옵니다. 무엇이 헛된 기대였는지 분명해져요.', en:'A sense of reality returns. It becomes clear which hopes were empty.' },
    t:{ love:{ ko:'그럴듯한 상대가 여럿인 상황이 관건입니다. 실체를 보면 도움이 됩니다.', en:'Several plausible people at once. Looking for substance helps.' },
        work:{ ko:'제안의 실체가 문제입니다. 그림과 계획을 가르면 좋습니다.', en:'Whether the offers are real. Separate pictures from plans.' },
        money:{ ko:'솔깃한 이야기의 근거가 핵심입니다. 확인하면 편합니다.', en:'The basis behind a tempting story. Verifying helps.' },
        rel:{ ko:'겉모습으로 사람을 고르고 있지 않은지가 주제입니다.', en:'Whether you are choosing people by their surface.' } } },
  { id:'cups-08', arcana:'minor', num:8, suit:'cups',
    name:{ ko:'컵 8', en:'Eight of Cups' },
    k:{ ko:['떠남','포기','탐색'], en:['Leaving','Release','Search'] },
    u:{ ko:'나쁘지 않은데도 부족합니다. 채워지지 않는 자리를 등지고 떠날 때예요.', en:'Nothing is wrong and still it does not fill you. Time to turn your back on the place that will not.' },
    r:{ ko:'떠나지 못하고 맴돕니다. 미련과 결심 사이에서 왔다 갔다 하는 중입니다.', en:'You cannot leave and keep circling. You move between regret and resolve.' },
    t:{ love:{ ko:'나쁘지 않은데 채워지지 않는 이유가 관건입니다.', en:'Why something fine still does not fill you.' },
        work:{ ko:'지금 자리를 떠날 마음이 문제입니다.', en:'The wish to leave where you are.' },
        money:{ ko:'붙들던 것을 정리할지가 핵심입니다.', en:'Whether to cut what you have been holding.' },
        rel:{ ko:'오래된 무리에서 빠져나오는 일이 주제입니다.', en:'Slipping quietly out of an old circle.' } } },
  { id:'cups-09', arcana:'minor', num:9, suit:'cups',
    name:{ ko:'컵 9', en:'Nine of Cups' },
    k:{ ko:['만족','소원','흡족'], en:['Satisfaction','Wish','Contentment'] },
    u:{ ko:'바라던 것이 이루어집니다. 누려도 되는 시기이니 충분히 만끽하세요.', en:'What you wanted arrives. This is a season to enjoy, so take it in fully.' },
    r:{ ko:'채워도 허합니다. 원하던 것을 얻고도 만족을 못 느낄 수 있어요.', en:'It fills and still feels hollow. You may get what you wanted and feel nothing.' },
    t:{ love:{ ko:'바라던 관계에 닿았는지가 관건입니다.', en:'Whether you reached the bond you wanted.' },
        work:{ ko:'원하던 결과가 주제입니다.', en:'The result you were after is the theme.' },
        money:{ ko:'쓰고 싶던 것에 쓸 여유가 핵심입니다.', en:'Room to spend on what you wanted is the core.' },
        rel:{ ko:'사람 복이 문제입니다.', en:'Good fortune in people is the issue.' } } },
  { id:'cups-10', arcana:'minor', num:10, suit:'cups',
    name:{ ko:'컵 10', en:'Ten of Cups' },
    k:{ ko:['행복','가정','완성된 관계'], en:['Happiness','Home','Fulfilment'] },
    u:{ ko:'감정적으로 가장 충만한 카드입니다. 함께하는 사람들과의 조화가 이루어져요.', en:'The fullest card of feeling. Harmony with the people you share your life with.' },
    r:{ ko:'이상적인 그림과 현실이 어긋납니다. 가족이나 가까운 관계에 균열이 있어요.', en:'The picture and the reality do not line up. There is a crack in family or in someone close.' },
    t:{ love:{ ko:'오래 갈 관계인지가 관건입니다.', en:'Whether this is a bond for the long run.' },
        work:{ ko:'사람들과의 조화가 성과로 이어지는지가 문제입니다.', en:'Whether harmony with people turns into results.' },
        money:{ ko:'함께 쓰는 돈이 핵심입니다.', en:'Money spent together is the core.' },
        rel:{ ko:'마음 편한 사람들이 주제입니다.', en:'The people you are easy with are the theme.' } } },
  { id:'cups-11', arcana:'minor', num:11, suit:'cups',
    name:{ ko:'컵 페이지', en:'Page of Cups' },
    k:{ ko:['설렘','감수성','고백'], en:['Flutter','Sensitivity','Confession'] },
    u:{ ko:'순수한 마음이 움직입니다. 뜻밖의 고백이나 다정한 소식이 있어요.', en:'A plain heart moves. An unexpected confession or a kind message.' },
    r:{ ko:'감정이 미숙합니다. 상처받을까 봐 마음을 숨기거나 응석으로 표현해요.', en:'The feeling is young. You hide it for fear of hurt, or express it as sulking.' },
    t:{ love:{ ko:'뜻밖의 고백과 다정한 연락이 관건입니다.', en:'An unexpected confession or a kind message.' },
        work:{ ko:'마음이 가는 제안이 문제입니다.', en:'An offer you feel drawn to.' },
        money:{ ko:'기분에 열리는 지갑이 핵심입니다. 하루 두고 보면 도움이 됩니다.', en:'A wallet that opens by mood. A day\'s pause helps.' },
        rel:{ ko:'순수하게 다가오는 사람이 주제입니다.', en:'Someone approaching plainly is the theme.' } } },
  { id:'cups-12', arcana:'minor', num:12, suit:'cups',
    name:{ ko:'컵 나이트', en:'Knight of Cups' },
    k:{ ko:['낭만','제안','다가옴'], en:['Romance','Offer','Approach'] },
    u:{ ko:'마음을 담아 다가오는 사람 혹은 제안입니다. 아름답고 진심 어린 접근이에요.', en:'Someone or something comes toward you with feeling behind it. A beautiful and sincere approach.' },
    r:{ ko:'말뿐인 낭만입니다. 기분에 따라 흔들리고 약속을 지키지 못합니다.', en:'Romance in words only. It shifts with mood and does not keep promises.' },
    t:{ love:{ ko:'다가오는 진심의 무게가 관건입니다.', en:'The weight of the sincerity coming toward you.' },
        work:{ ko:'제안의 조건이 문제입니다. 말과 조건이 같은지 보면 좋습니다.', en:'The terms of the offer. Check that words and terms agree.' },
        money:{ ko:'보기 좋은 것에 쓰는 돈이 핵심입니다.', en:'Money spent on what looks good is the core.' },
        rel:{ ko:'먼저 손 내미는 사람이 주제입니다.', en:'The one who reaches out first is the theme.' } } },
  { id:'cups-13', arcana:'minor', num:13, suit:'cups',
    name:{ ko:'컵 퀸', en:'Queen of Cups' },
    k:{ ko:['공감','포용','직관'], en:['Empathy','Holding','Intuition'] },
    u:{ ko:'상대의 마음을 깊이 읽고 품어줍니다. 감정을 다루는 데 성숙한 태도예요.', en:'You read the other person deeply and hold them. A mature way with feeling.' },
    r:{ ko:'감정에 잠식되거나 남에게 휘둘립니다. 경계를 세워야 할 때입니다.', en:'You are flooded by feeling or swayed by others. Time to set a boundary.' },
    t:{ love:{ ko:'마음을 읽어주는 깊이가 관건입니다.', en:'The depth of being understood.' },
        work:{ ko:'사람을 챙기는 자리가 주제입니다.', en:'A seat where looking after people is the work.' },
        money:{ ko:'직관과 숫자 중 무엇을 볼지가 핵심입니다. 둘 다 보면 편합니다.', en:'Instinct or the numbers. Looking at both helps.' },
        rel:{ ko:'기대오는 사람이 많아지는 상황입니다. 선을 두면 도움이 됩니다.', en:'More people leaning on you. A boundary helps.' } } },
  { id:'cups-14', arcana:'minor', num:14, suit:'cups',
    name:{ ko:'컵 킹', en:'King of Cups' },
    k:{ ko:['안정','성숙','조율'], en:['Steadiness','Maturity','Mediation'] },
    u:{ ko:'격한 감정 속에서도 흔들리지 않습니다. 사람들의 마음을 조율하는 어른의 자리예요.', en:'You do not waver inside strong feeling. The adult\'s seat, tuning what people feel.' },
    r:{ ko:'감정을 억누르다 폭발합니다. 겉은 차분한데 속이 곪아 있어요.', en:'You press feeling down until it bursts. Calm outside, festering inside.' },
    t:{ love:{ ko:'흔들림 없이 품는 힘이 관건입니다.', en:'The strength to hold without wavering.' },
        work:{ ko:'격한 상황을 조율하는 역할이 주제입니다.', en:'The role of tuning a heated situation.' },
        money:{ ko:'감정에 휘둘리지 않는 관리가 핵심입니다.', en:'Management that is not swayed by feeling.' },
        rel:{ ko:'사람들 사이를 중재하는 자리입니다.', en:'The seat of mediating between people.' } } },

  // ── 소드 (공기 / 사고·갈등) ──
  { id:'swords-01', arcana:'minor', num:1, suit:'swords',
    name:{ ko:'소드 에이스', en:'Ace of Swords' },
    k:{ ko:['명료함','진실','돌파'], en:['Clarity','Truth','Breakthrough'] },
    u:{ ko:'생각이 단칼에 정리됩니다. 진실을 말하거나 결단을 내리기 좋은 시기예요.', en:'Thinking resolves in one stroke. A good time to say the truth or make the call.' },
    r:{ ko:'혼란과 왜곡입니다. 잘못된 정보로 판단하고 있을 수 있어요.', en:'Confusion and distortion. You may be judging on wrong information.' },
    t:{ love:{ ko:'말할 것을 말할 때인가가 관건입니다. 미뤄둔 이야기를 꺼내면 도움이 됩니다.', en:'Whether it is time to say it. Raising what you postponed helps.' },
        work:{ ko:'생각이 정리됐는지가 문제입니다.', en:'Whether the thinking has settled.' },
        money:{ ko:'숫자를 정확히 보는 일이 핵심입니다.', en:'Seeing the numbers exactly is the core.' },
        rel:{ ko:'짚어야 할 것을 짚는 자리입니다.', en:'The place where what needs naming gets named.' } } },
  { id:'swords-02', arcana:'minor', num:2, suit:'swords',
    name:{ ko:'소드 2', en:'Two of Swords' },
    k:{ ko:['교착','회피','보류'], en:['Deadlock','Avoidance','Hold'] },
    u:{ ko:'보지 않으려고 눈을 가린 상태입니다. 결정하지 않는 것도 결정이에요.', en:'Your eyes are covered so you do not have to look. Not deciding is also a decision.' },
    r:{ ko:'가렸던 눈을 뜹니다. 미뤄둔 선택을 마주해야 할 때가 왔어요.', en:'The blindfold comes off. The choice you deferred is in front of you.' },
    t:{ love:{ ko:'마음을 정하지 못하고 있는 상태가 관건입니다.', en:'The state of not being able to decide.' },
        work:{ ko:'미루는 결정이 문제입니다. 기한을 정해두면 도움이 됩니다.', en:'The deferred decision. Setting a deadline helps.' },
        money:{ ko:'어느 쪽에도 손대지 않는 상태가 핵심입니다.', en:'The state of touching neither side.' },
        rel:{ ko:'어느 편도 들지 않는 자리가 주제입니다.', en:'The seat of taking nobody\'s side.' } } },
  { id:'swords-03', arcana:'minor', num:3, suit:'swords',
    name:{ ko:'소드 3', en:'Three of Swords' },
    k:{ ko:['상심','이별','아픈 진실'], en:['Heartbreak','Parting','Hard truth'] },
    u:{ ko:'아프지만 분명한 사실이 마음을 찌릅니다. 슬픔을 축소하지 말고 겪어내야 합니다.', en:'A clear fact pierces, and it hurts. Do not shrink the grief; go through it.' },
    r:{ ko:'회복이 시작되지만 아직 흉터가 남았습니다. 아픔을 끌어안고 있을 수도 있어요.', en:'Recovery starts but the scar is still there. You may also be holding the pain close.' },
    t:{ love:{ ko:'아프지만 분명한 사실이 관건입니다. 슬픔을 축소하지 않으면 도움이 됩니다.', en:'A painful but clear fact. Not shrinking the grief helps.' },
        work:{ ko:'거절이나 통보가 문제입니다.', en:'A refusal or a notice is the issue.' },
        money:{ ko:'확정된 손실이 핵심입니다. 그대로 적어두면 편합니다.', en:'A confirmed loss. Write it down as it is.' },
        rel:{ ko:'믿던 사람에게서 오는 상처가 주제입니다.', en:'Hurt from someone you trusted.' } } },
  { id:'swords-04', arcana:'minor', num:4, suit:'swords',
    name:{ ko:'소드 4', en:'Four of Swords' },
    k:{ ko:['휴식','회복','정지'], en:['Rest','Recovery','Pause'] },
    u:{ ko:'멈추고 쉬어야 합니다. 지금의 정지는 후퇴가 아니라 정비예요.', en:'Stop and rest. This halt is maintenance, not retreat.' },
    r:{ ko:'쉬지 못하고 소진됩니다. 혹은 이제 다시 움직일 때가 되었어요.', en:'You cannot rest and are burning down. Or it is time to move again.' },
    t:{ love:{ ko:'거리를 두고 쉴 때인가가 관건입니다.', en:'Whether it is time to step back and rest.' },
        work:{ ko:'멈추고 정비하는 시간이 문제입니다.', en:'The time of stopping to service things.' },
        money:{ ko:'움직이지 않고 두는 선택이 핵심입니다.', en:'The choice of not moving at all.' },
        rel:{ ko:'연락을 줄이는 것이 회복인지 도피인지 보면 좋습니다.', en:'Whether less contact is recovery or avoidance.' } } },
  { id:'swords-05', arcana:'minor', num:5, suit:'swords',
    name:{ ko:'소드 5', en:'Five of Swords' },
    k:{ ko:['상처뿐인 승리','갈등','자존심'], en:['Hollow win','Conflict','Pride'] },
    u:{ ko:'이겨도 남는 게 없습니다. 옳음을 증명하려다 관계를 잃을 수 있어요.', en:'Winning leaves nothing behind. Proving you were right can cost the relationship.' },
    r:{ ko:'갈등을 정리하고 화해로 향합니다. 혹은 앙금이 오래 남습니다.', en:'The conflict resolves toward peace. Or the residue stays a long time.' },
    t:{ love:{ ko:'이겨서 무엇이 남는지가 관건입니다.', en:'What is left after winning.' },
        work:{ ko:'옳음과 관계 중 무엇을 지킬지가 문제입니다. 물러설 지점을 정해두면 좋습니다.', en:'Being right or keeping the person. Decide where you would yield.' },
        money:{ ko:'따지다 놓치는 것이 없는지가 핵심입니다.', en:'Whether arguing costs you more.' },
        rel:{ ko:'말로 이기는 일의 대가가 주제입니다.', en:'The price of winning with words.' } } },
  { id:'swords-06', arcana:'minor', num:6, suit:'swords',
    name:{ ko:'소드 6', en:'Six of Swords' },
    k:{ ko:['이동','벗어남','전환'], en:['Passage','Leaving','Transition'] },
    u:{ ko:'힘든 자리를 떠나 조용한 곳으로 옮겨갑니다. 극적이지 않지만 확실한 회복이에요.', en:'You leave a hard place for a quieter one. Undramatic, but a real recovery.' },
    r:{ ko:'떠나지 못하고 같은 자리를 맴돕니다. 과거가 계속 따라옵니다.', en:'You cannot leave and circle the same spot. The past keeps following.' },
    t:{ love:{ ko:'힘든 자리에서 빠져나오는 일이 관건입니다.', en:'Getting out of a hard bond.' },
        work:{ ko:'자리를 옮기며 한숨 돌리는 국면입니다.', en:'Moving and catching your breath.' },
        money:{ ko:'조금씩 나아지는 흐름이 핵심입니다.', en:'The slow improvement is the core.' },
        rel:{ ko:'무거운 사람들과의 거리가 주제입니다.', en:'Distance from heavy people.' } } },
  { id:'swords-07', arcana:'minor', num:7, suit:'swords',
    name:{ ko:'소드 7', en:'Seven of Swords' },
    k:{ ko:['전략','기만','은밀함'], en:['Strategy','Deception','Stealth'] },
    u:{ ko:'정면 승부 대신 우회하는 상황입니다. 숨기는 사람이 있거나 스스로 감추는 것이 있어요.', en:'A situation that goes around rather than head-on. Someone is hiding something, or you are.' },
    r:{ ko:'속임수가 드러나거나 양심이 자백합니다. 솔직해질 기회입니다.', en:'The trick comes out, or conscience confesses. A chance to be straight.' },
    t:{ love:{ ko:'감추는 것이 있는지가 관건입니다.', en:'Whether something is being hidden.' },
        work:{ ko:'정면과 우회 중 무엇을 택할지가 문제입니다.', en:'Head-on or around is the question.' },
        money:{ ko:'새는 곳이 있는지가 핵심입니다. 내역을 훑어보면 도움이 됩니다.', en:'Whether something is leaking. A look through the ledger helps.' },
        rel:{ ko:'뒤에서 도는 말이 주제입니다.', en:'Words moving behind your back.' } } },
  { id:'swords-08', arcana:'minor', num:8, suit:'swords',
    name:{ ko:'소드 8', en:'Eight of Swords' },
    k:{ ko:['속박감','무력감','자기제한'], en:['Restriction','Powerlessness','Self-limit'] },
    u:{ ko:'갇힌 것 같지만 결박은 생각보다 헐겁습니다. 스스로 만든 한계가 가장 큰 벽이에요.', en:'It feels like a cage, but the binding is looser than it looks. The limit you made is the biggest wall.' },
    r:{ ko:'벗어나기 시작합니다. 두려움의 정체를 알면 길이 보여요.', en:'You begin to get out. Knowing what the fear actually is shows the way.' },
    t:{ love:{ ko:'스스로 만든 한계가 관건입니다. 결박이 정말 단단한지 보면 도움이 됩니다.', en:'A limit you built yourself. Test whether the binding is really tight.' },
        work:{ ko:'갇힌 것 같은 상황이 문제입니다.', en:'The situation that feels closed.' },
        money:{ ko:'방법이 없다고 단정하고 있지 않은지가 핵심입니다.', en:'Whether you have decided too soon that there is no way.' },
        rel:{ ko:'눈치 보느라 말을 못 하는 자리가 주제입니다.', en:'The place where you cannot speak for watching others.' } } },
  { id:'swords-09', arcana:'minor', num:9, suit:'swords',
    name:{ ko:'소드 9', en:'Nine of Swords' },
    k:{ ko:['불안','걱정','불면'], en:['Anxiety','Worry','Sleeplessness'] },
    u:{ ko:'밤에 커지는 걱정입니다. 실제 상황보다 머릿속이 훨씬 가혹해요.', en:'Worry that grows at night. Your head is far harsher than the situation.' },
    r:{ ko:'최악의 상상에서 빠져나옵니다. 털어놓으면 크게 가벼워집니다.', en:'You come out of the worst imagining. Saying it out loud lightens it a great deal.' },
    t:{ love:{ ko:'머릿속과 실제의 차이가 관건입니다.', en:'The gap between your head and the facts.' },
        work:{ ko:'최악을 상상하는 밤이 문제입니다.', en:'Nights of imagining the worst.' },
        money:{ ko:'걱정이 실제 사정보다 큰지가 핵심입니다. 숫자를 직접 보면 도움이 됩니다.', en:'Whether the worry is larger than the accounts. Look at them directly.' },
        rel:{ ko:'혼자 키운 오해가 주제입니다. 물어보면 가벼워집니다.', en:'A misunderstanding grown alone. Asking makes it lighter.' } } },
  { id:'swords-10', arcana:'minor', num:10, suit:'swords',
    name:{ ko:'소드 10', en:'Ten of Swords' },
    k:{ ko:['바닥','종결','항복'], en:['Bottom','Ending','Surrender'] },
    u:{ ko:'더 나빠질 것이 없는 바닥입니다. 끝났다는 사실을 인정하면 해가 뜹니다.', en:'The floor, with nothing worse below. Admit it is over and the sun comes up.' },
    r:{ ko:'회복이 시작되지만 더디거나, 끝난 일을 계속 되새깁니다.', en:'Recovery starts but slowly, or you keep chewing over what ended.' },
    t:{ love:{ ko:'끝을 인정할 것인가가 관건입니다.', en:'Whether to admit the end.' },
        work:{ ko:'더 나빠질 것이 없는 바닥이 문제입니다.', en:'The floor with nothing worse below.' },
        money:{ ko:'정리하고 다시 시작할지가 핵심입니다.', en:'Whether to clear it and start again.' },
        rel:{ ko:'등을 돌린 사람이 주제입니다.', en:'Someone who has turned away.' } } },
  { id:'swords-11', arcana:'minor', num:11, suit:'swords',
    name:{ ko:'소드 페이지', en:'Page of Swords' },
    k:{ ko:['호기심','관찰','소식'], en:['Curiosity','Watching','News'] },
    u:{ ko:'예리하게 캐묻고 배웁니다. 정보와 관련된 소식이 들어와요.', en:'You ask sharply and learn. News related to information arrives.' },
    r:{ ko:'말이 앞서거나 험담이 됩니다. 확인 없이 퍼뜨리지 마세요.', en:'Words run ahead, or turn into gossip. Do not pass anything on unverified.' },
    t:{ love:{ ko:'캐묻고 살피는 마음이 관건입니다.', en:'The urge to ask and watch.' },
        work:{ ko:'들어오는 정보와 소식이 문제입니다.', en:'Incoming information and news.' },
        money:{ ko:'아직 알아보는 단계인지가 핵심입니다. 넣기 전에 확인하면 좋습니다.', en:'Whether this is still the looking stage. Check once more before committing.' },
        rel:{ ko:'옮겨 다니는 말이 주제입니다. 확인 없이 옮기지 않으면 도움이 됩니다.', en:'Words travelling. Not passing them on unverified helps.' } } },
  { id:'swords-12', arcana:'minor', num:12, suit:'swords',
    name:{ ko:'소드 나이트', en:'Knight of Swords' },
    k:{ ko:['속도','직진','논쟁'], en:['Speed','Directness','Argument'] },
    u:{ ko:'목표를 향해 곧장 돌진합니다. 명확하고 빠르지만 배려는 부족해요.', en:'You charge straight at the goal. Clear and fast, but short on consideration.' },
    r:{ ko:'공격적이고 성급합니다. 말로 사람을 베고 있을 수 있어요.', en:'Aggressive and hasty. You may be cutting people with words.' },
    t:{ love:{ ko:'직진하는 마음과 배려 사이가 관건입니다.', en:'Between going straight and being considerate.' },
        work:{ ko:'밀어붙이는 속도가 문제입니다.', en:'The speed of the push.' },
        money:{ ko:'성급함이 손해로 이어지는지가 핵심입니다.', en:'Whether haste turns into loss.' },
        rel:{ ko:'날카로운 말이 주제입니다. 한 박자 두면 도움이 됩니다.', en:'Sharp words. A beat\'s pause helps.' } } },
  { id:'swords-13', arcana:'minor', num:13, suit:'swords',
    name:{ ko:'소드 퀸', en:'Queen of Swords' },
    k:{ ko:['통찰','객관','독립'], en:['Insight','Objectivity','Independence'] },
    u:{ ko:'감정에 휘둘리지 않고 핵심을 봅니다. 솔직하고 공정한 판단이 힘이 돼요.', en:'You see the core without being swayed. Honest, fair judgement is the strength here.' },
    r:{ ko:'냉소와 날 선 말이 벽을 만듭니다. 방어가 지나쳤어요.', en:'Cynicism and edged words build a wall. The defence has gone too far.' },
    t:{ love:{ ko:'감정을 걷어내고 볼 수 있는가가 관건입니다.', en:'Whether you can look with the feeling set aside.' },
        work:{ ko:'핵심을 짚는 눈이 주제입니다.', en:'The eye that finds the core.' },
        money:{ ko:'냉정한 판단이 핵심입니다.', en:'Cool judgement is the core.' },
        rel:{ ko:'선을 어디에 그을지가 문제입니다.', en:'Where to draw the line.' } } },
  { id:'swords-14', arcana:'minor', num:14, suit:'swords',
    name:{ ko:'소드 킹', en:'King of Swords' },
    k:{ ko:['이성','원칙','권위'], en:['Reason','Principle','Authority'] },
    u:{ ko:'논리와 원칙으로 판단합니다. 전문가의 조언이나 공적인 결정과 인연이 있어요.', en:'You judge by logic and principle. Close to expert counsel and formal decisions.' },
    r:{ ko:'경직된 논리가 사람을 억누릅니다. 옳은 말도 방식이 틀리면 폭력이 됩니다.', en:'Rigid logic presses people down. Even a right thing said wrong becomes force.' },
    t:{ love:{ ko:'이성과 다정함 사이가 관건입니다.', en:'Between reason and warmth.' },
        work:{ ko:'원칙과 논리로 판단하는 자리입니다.', en:'The seat of judging by principle and logic.' },
        money:{ ko:'전문가의 조언을 따를지가 핵심입니다.', en:'Whether to follow expert counsel.' },
        rel:{ ko:'판단해주는 어른의 자리가 주제입니다.', en:'The seat of the one who judges.' } } },

  // ── 펜타클 (흙 / 물질·현실) ──
  { id:'pents-01', arcana:'minor', num:1, suit:'pents',
    name:{ ko:'펜타클 에이스', en:'Ace of Pentacles' },
    k:{ ko:['기회','종잣돈','현실화'], en:['Opportunity','Seed money','Made real'] },
    u:{ ko:'실질적인 기회가 손에 들어옵니다. 돈, 일, 건강 등 현실의 토대가 놓이는 시작이에요.', en:'A concrete opportunity lands in your hand. A foundation is laid in money, work or health.' },
    r:{ ko:'기회를 놓치거나 계산이 어긋납니다. 조건을 다시 따져보세요.', en:'You miss the chance or the arithmetic is off. Look at the terms again.' },
    t:{ love:{ ko:'실질적으로 이어질 만한 인연인가가 관건입니다.', en:'Whether this is a bond that can become real.' },
        work:{ ko:'손에 잡히는 기회가 문제입니다.', en:'A chance you can hold in your hand.' },
        money:{ ko:'목돈이나 새 수입원이 핵심입니다.', en:'A lump sum or a new source is the core.' },
        rel:{ ko:'도움이 되는 사람과의 만남이 주제입니다.', en:'Meeting someone who actually helps.' } } },
  { id:'pents-02', arcana:'minor', num:2, suit:'pents',
    name:{ ko:'펜타클 2', en:'Two of Pentacles' },
    k:{ ko:['저글링','유연함','우선순위'], en:['Juggling','Flexibility','Priority'] },
    u:{ ko:'여러 일을 동시에 굴리는 중입니다. 리듬만 유지하면 충분히 해낼 수 있어요.', en:'You are keeping several things in the air. Hold the rhythm and you can manage it.' },
    r:{ ko:'과부하로 공을 떨어뜨립니다. 하나는 내려놓아야 합니다.', en:'Overload makes you drop one. Something has to go down.' },
    t:{ love:{ ko:'다른 일에 치여 소홀하지 않은지가 관건입니다.', en:'Whether other things are crowding it out.' },
        work:{ ko:'여러 일을 굴리는 리듬이 문제입니다. 하나는 내려놓으면 도움이 됩니다.', en:'The rhythm of running several things. Putting one down helps.' },
        money:{ ko:'들어오고 나가는 것의 균형이 핵심입니다.', en:'The balance of in and out is the core.' },
        rel:{ ko:'여러 사람을 챙기는 부담이 주제입니다.', en:'The load of looking after many people.' } } },
  { id:'pents-03', arcana:'minor', num:3, suit:'pents',
    name:{ ko:'펜타클 3', en:'Three of Pentacles' },
    k:{ ko:['협업','기술','인정'], en:['Collaboration','Craft','Recognition'] },
    u:{ ko:'각자의 실력이 모여 결과를 만듭니다. 배우고 협력할수록 좋아지는 국면이에요.', en:'Separate skills combine into a result. It improves the more you learn and work together.' },
    r:{ ko:'손발이 안 맞거나 실력이 부족합니다. 역할을 다시 정리해야 해요.', en:'You are out of step, or short on skill. The roles need sorting again.' },
    t:{ love:{ ko:'함께 무언가를 만들어가는 관계인가가 관건입니다.', en:'Whether you are building something together.' },
        work:{ ko:'실력이 모여 결과가 되는지가 문제입니다.', en:'Whether combined skill turns into a result.' },
        money:{ ko:'일한 만큼 값이 매겨지는지가 핵심입니다.', en:'Whether the work is priced as it was done.' },
        rel:{ ko:'각자의 역할이 정해졌는지가 주제입니다.', en:'Whether each person\'s role is settled.' } } },
  { id:'pents-04', arcana:'minor', num:4, suit:'pents',
    name:{ ko:'펜타클 4', en:'Four of Pentacles' },
    k:{ ko:['보존','인색','통제'], en:['Keeping','Tightness','Control'] },
    u:{ ko:'가진 것을 꽉 쥐고 지킵니다. 안정적이지만 그만큼 새로운 것이 못 들어와요.', en:'You hold what you have and guard it. Stable, and equally closed to anything new.' },
    r:{ ko:'집착을 놓거나, 반대로 헤프게 흘려보냅니다. 돈의 흐름을 점검하세요.', en:'You loosen the grip, or let it run out carelessly. Check where the money moves.' },
    t:{ love:{ ko:'붙잡아두려는 마음이 관건입니다. 상대가 답답해하지 않는지 보면 도움이 됩니다.', en:'The wish to keep hold. Watch whether it stifles the other person.' },
        work:{ ko:'자리를 지키느라 새것을 못 받는지가 문제입니다.', en:'Whether guarding your place blocks the new.' },
        money:{ ko:'쥐고 있는 것과 굴리는 것 사이가 핵심입니다.', en:'Between holding and putting to work.' },
        rel:{ ko:'마음을 내주지 않는 태도가 주제입니다.', en:'The habit of not offering yourself.' } } },
  { id:'pents-05', arcana:'minor', num:5, suit:'pents',
    name:{ ko:'펜타클 5', en:'Five of Pentacles' },
    k:{ ko:['결핍','소외','고립'], en:['Lack','Exclusion','Isolation'] },
    u:{ ko:'물질적으로든 정서적으로든 춥습니다. 바로 옆에 도움의 문이 있는데 못 보고 지나가요.', en:'Cold, in money or in feeling. There is a door of help right beside you and you walk past it.' },
    r:{ ko:'어려운 시기가 지나갑니다. 도움을 청하면 상황이 달라져요.', en:'The hard season passes. Asking for help changes the picture.' },
    t:{ love:{ ko:'마음이 춥고 기댈 데가 없는 상태가 관건입니다.', en:'Being cold with nowhere to lean.' },
        work:{ ko:'자리에서 밀려난 느낌이 문제입니다.', en:'The feeling of being pushed out of a place.' },
        money:{ ko:'빠듯한 사정이 핵심입니다. 도움을 청하면 달라집니다.', en:'Tight circumstances. Asking for help changes it.' },
        rel:{ ko:'무리 밖에 있는 느낌이 주제입니다. 문은 생각보다 가까이 있습니다.', en:'Feeling outside the circle. The door is nearer than it looks.' } } },
  { id:'pents-06', arcana:'minor', num:6, suit:'pents',
    name:{ ko:'펜타클 6', en:'Six of Pentacles' },
    k:{ ko:['나눔','도움','균형'], en:['Sharing','Help','Balance'] },
    u:{ ko:'주고받음이 원활합니다. 도움을 받거나 베풀 기회가 생겨요.', en:'Giving and taking move easily. A chance to receive help or to offer it.' },
    r:{ ko:'주고받음이 불공평합니다. 조건이 붙은 호의를 조심하세요.', en:'The exchange is uneven. Be careful of goodwill with conditions attached.' },
    t:{ love:{ ko:'주고받는 것이 고른지가 관건입니다.', en:'Whether give and take is even.' },
        work:{ ko:'도움을 받거나 베푸는 일이 문제입니다.', en:'Receiving help or offering it.' },
        money:{ ko:'빌리고 빌려주는 일이 핵심입니다. 조건을 적어두면 편합니다.', en:'Lending and borrowing. Write the terms down.' },
        rel:{ ko:'손 내밀어주는 사람이 주제입니다.', en:'Someone reaching a hand out.' } } },
  { id:'pents-07', arcana:'minor', num:7, suit:'pents',
    name:{ ko:'펜타클 7', en:'Seven of Pentacles' },
    k:{ ko:['인내','중간점검','투자'], en:['Patience','Review','Investment'] },
    u:{ ko:'심어둔 것이 자라는 중입니다. 지금 캐면 이릅니다. 기다림도 노동이에요.', en:'What you planted is growing. Pull it now and it is early. Waiting is also labour.' },
    r:{ ko:'성과가 없어 초조합니다. 방향이 틀렸다면 갈아엎는 것도 답입니다.', en:'Nothing shows and you are restless. If the direction is wrong, turning the soil is an answer too.' },
    t:{ love:{ ko:'아직 이른지 여물었는지가 관건입니다. 조금 더 두고 보면 도움이 됩니다.', en:'Early or ripe. Leaving it a little longer helps.' },
        work:{ ko:'심어둔 것이 자라는 중간 지점입니다.', en:'The middle point of something still growing.' },
        money:{ ko:'성과가 없어 보이는 시간이 핵심입니다.', en:'The stretch where nothing seems to show.' },
        rel:{ ko:'들인 시간이 여물었는지가 주제입니다.', en:'Whether the time you put in has ripened.' } } },
  { id:'pents-08', arcana:'minor', num:8, suit:'pents',
    name:{ ko:'펜타클 8', en:'Eight of Pentacles' },
    k:{ ko:['숙련','반복','성실'], en:['Craft','Repetition','Diligence'] },
    u:{ ko:'묵묵히 갈고닦는 시기입니다. 지루한 반복이 실력으로 쌓여요.', en:'A season of quiet honing. Dull repetition stacks into skill.' },
    r:{ ko:'대충 하거나 의미를 잃었습니다. 완벽주의로 진도가 안 나갈 수도 있어요.', en:'You are going through the motions or have lost the point. Perfectionism may also be stalling you.' },
    t:{ love:{ ko:'꾸준함이 관건입니다.', en:'Steadiness is what matters.' },
        work:{ ko:'지루한 반복이 실력이 되는지가 문제입니다.', en:'Whether dull repetition becomes skill.' },
        money:{ ko:'착실히 모으는 방식이 핵심입니다.', en:'Saving steadily is the core.' },
        rel:{ ko:'자주 보는 사이의 무게가 주제입니다.', en:'The weight of the people you see often.' } } },
  { id:'pents-09', arcana:'minor', num:9, suit:'pents',
    name:{ ko:'펜타클 9', en:'Nine of Pentacles' },
    k:{ ko:['자립','여유','품격'], en:['Self-reliance','Ease','Poise'] },
    u:{ ko:'스스로 일군 것으로 누리는 여유입니다. 혼자서도 충분히 풍요로워요.', en:'Ease enjoyed from what you built yourself. You are rich enough alone.' },
    r:{ ko:'겉만 화려하거나 의존적입니다. 여유를 위해 무엇을 희생했는지 보세요.', en:'Fine on the surface, or dependent. Look at what the ease cost you.' },
    t:{ love:{ ko:'혼자서도 충분한지가 관건입니다.', en:'Whether you are enough on your own.' },
        work:{ ko:'실력으로 만든 자리가 주제입니다.', en:'A place made by your own skill.' },
        money:{ ko:'스스로 일군 여유가 핵심입니다.', en:'Ease you built yourself is the core.' },
        rel:{ ko:'사람을 가려 만나는 태도가 문제입니다.', en:'The habit of choosing who to see.' } } },
  { id:'pents-10', arcana:'minor', num:10, suit:'pents',
    name:{ ko:'펜타클 10', en:'Ten of Pentacles' },
    k:{ ko:['안정','유산','장기적 기반'], en:['Stability','Legacy','Long base'] },
    u:{ ko:'오래 갈 토대가 만들어집니다. 가족, 자산, 장기 계약과 인연이 깊어요.', en:'A base is made that will last. Close to family, assets and long contracts.' },
    r:{ ko:'재정이나 가족 문제로 갈등이 생깁니다. 장기적 관점이 흔들려요.', en:'Money or family creates friction. The long view is unsteady.' },
    t:{ love:{ ko:'결혼이나 가족 이야기가 관건입니다.', en:'Marriage or family is what is at stake.' },
        work:{ ko:'오래 갈 기반이 문제입니다.', en:'A base built to last.' },
        money:{ ko:'자산과 장기 계약이 핵심입니다.', en:'Assets and long contracts are the core.' },
        rel:{ ko:'가족과 오래된 사람들이 주제입니다.', en:'Family and the people who have been there.' } } },
  { id:'pents-11', arcana:'minor', num:11, suit:'pents',
    name:{ ko:'펜타클 페이지', en:'Page of Pentacles' },
    k:{ ko:['학습','착실함','기회'], en:['Study','Steadiness','Chance'] },
    u:{ ko:'배우고 준비하는 자세입니다. 작지만 확실한 기회가 들어와요.', en:'A posture of learning and preparing. A small but definite chance arrives.' },
    r:{ ko:'미루거나 산만합니다. 계획만 있고 실행이 없어요.', en:'You put it off or scatter. Plans without execution.' },
    t:{ love:{ ko:'조심스럽게 알아가는 단계가 관건입니다.', en:'The careful stage of getting to know.' },
        work:{ ko:'배우고 준비하는 자리가 문제입니다.', en:'The seat of learning and preparing.' },
        money:{ ko:'작지만 확실한 기회가 핵심입니다.', en:'A small but definite chance.' },
        rel:{ ko:'성실하게 다가오는 사람이 주제입니다.', en:'Someone approaching in earnest.' } } },
  { id:'pents-12', arcana:'minor', num:12, suit:'pents',
    name:{ ko:'펜타클 나이트', en:'Knight of Pentacles' },
    k:{ ko:['꾸준함','신뢰','느린 전진'], en:['Constancy','Trust','Slow advance'] },
    u:{ ko:'느리지만 절대 멈추지 않습니다. 약속을 지키는 태도가 신뢰를 만들어요.', en:'Slow, and it never stops. Keeping the promise is what builds the trust.' },
    r:{ ko:'지나치게 굼뜨고 지루합니다. 변화를 거부하고 있어요.', en:'Too slow and dull. You are refusing change.' },
    t:{ love:{ ko:'느리지만 약속을 지키는 태도가 관건입니다.', en:'Slow, but keeps a promise.' },
        work:{ ko:'티 안 나게 나아가는 걸음이 문제입니다.', en:'The step that goes on without showing.' },
        money:{ ko:'조금씩 확실하게 느는 방식이 핵심입니다.', en:'The method of gaining a little at a time.' },
        rel:{ ko:'오래 곁에 있어줄 사람이 주제입니다.', en:'Someone who will stay a long while.' } } },
  { id:'pents-13', arcana:'minor', num:13, suit:'pents',
    name:{ ko:'펜타클 퀸', en:'Queen of Pentacles' },
    k:{ ko:['현실감각','돌봄','살림'], en:['Groundedness','Care','Household'] },
    u:{ ko:'실질적으로 챙기고 돌봅니다. 일과 생활을 동시에 굴리는 능력이 빛나요.', en:'You look after things practically. The knack of running work and life at once shows here.' },
    r:{ ko:'다 떠안다가 자기를 잃습니다. 물질에만 매달릴 수도 있어요.', en:'You take it all on and lose yourself. You may also be clinging to the material.' },
    t:{ love:{ ko:'실질적으로 챙겨주는 관계인가가 관건입니다.', en:'Whether the care is practical.' },
        work:{ ko:'일과 생활을 함께 굴리는 힘이 문제입니다.', en:'The strength of running work and life together.' },
        money:{ ko:'알뜰한 관리가 핵심입니다.', en:'Careful management is the core.' },
        rel:{ ko:'돌보는 자리가 주제입니다. 자신도 챙기면 도움이 됩니다.', en:'The role of feeding and tending. Look after yourself too.' } } },
  { id:'pents-14', arcana:'minor', num:14, suit:'pents',
    name:{ ko:'펜타클 킹', en:'King of Pentacles' },
    k:{ ko:['성취','안정','경영'], en:['Achievement','Stability','Stewardship'] },
    u:{ ko:'현실에서 결과를 만들어낸 사람입니다. 자산과 사람을 안정적으로 운용해요.', en:'Someone who made results in the real world. Assets and people run steadily.' },
    r:{ ko:'물질에 집착하거나 완고합니다. 성공이 목적을 잡아먹었어요.', en:'Clinging to the material, or immovable. Success has eaten the purpose.' },
    t:{ love:{ ko:'든든함과 무뚝뚝함 사이가 관건입니다.', en:'Between solid and unspoken.' },
        work:{ ko:'결과를 만들어내는 자리가 문제입니다.', en:'The seat where results are made.' },
        money:{ ko:'안정적으로 굴러가는 자산이 핵심입니다.', en:'Assets running steadily is the core.' },
        rel:{ ko:'사람과 돈을 함께 관리하는 자리가 주제입니다.', en:'The seat of managing people and money together.' } } },
];

export const LENS = {
  love: { ko:'연애', en:'Love' }, work: { ko:'일', en:'Work' },
  money:{ ko:'돈', en:'Money' }, rel:  { ko:'관계', en:'People' },
};

// 고르는 라벨은 상황으로, 카드 문장은 렌즈로 묶습니다.
// id는 공유 링크에 실리므로 바꾸지 않습니다.
export const TOPICS = [
  { id:'today', lens:'', label:{ ko:'오늘', en:'Today' } },
  { id:'crush', lens:'love', label:{ ko:'썸', en:'Crush' } },
  { id:'reunion', lens:'love', label:{ ko:'재회', en:'Getting back' } },
  { id:'confess', lens:'love', label:{ ko:'고백', en:'Telling them' } },
  { id:'jobmove', lens:'work', label:{ ko:'이직', en:'Changing jobs' } },
  { id:'jobhunt', lens:'work', label:{ ko:'취업', en:'Finding work' } },
  { id:'atwork', lens:'work', label:{ ko:'지금 일', en:'Work right now' } },
  { id:'money', lens:'money', label:{ ko:'돈', en:'Money' } },
  { id:'people', lens:'rel', label:{ ko:'사람 문제', en:'Someone difficult' } },
  { id:'cutoff', lens:'rel', label:{ ko:'손절', en:'Cutting ties' } },
];

export const SPREADS = {
  one: { name:{ ko:'원 카드', en:'One Card' },
    positions:{ ko:['지금 이 순간'], en:['This moment'] } },
  three: { name:{ ko:'쓰리 카드', en:'Three Cards' },
    positions:{ ko:['과거','현재','미래'], en:['Past','Present','Future'] } },
  act: { name:{ ko:'무엇을 할까', en:'What to Do' },
    positions:{ ko:['지금 상황','할 수 있는 일','그러면 어떻게 되나'], en:['Where you are','What you can do','Where that leads'] } },
  choice: { name:{ ko:'선택', en:'The Choice' },
    positions:{ ko:['지금 상황','첫 번째 길','첫 번째 길의 끝','두 번째 길','두 번째 길의 끝'], en:['Where you are','The first road','End of the first','The second road','End of the second'] } },
  horseshoe: { name:{ ko:'말굽', en:'Horseshoe' },
    positions:{ ko:['지나온 일','지금','숨은 영향','장애물','주변 사람들','조언','결과'], en:['What has passed','Now','Hidden influence','The obstacle','People around you','Advice','Outcome'] } },
  celtic: { name:{ ko:'켈틱 크로스', en:'Celtic Cross' },
    positions:{ ko:['현재 상황','장애물','토대(무의식)','과거','목표(의식)','가까운 미래','나의 태도','주변 환경','희망과 두려움','최종 결과'], en:['Present situation','What crosses it','Foundation','The past','What you aim at','Near future','Your stance','Around you','Hopes and fears','Outcome'] } },
  zodiac: { name:{ ko:'조디악', en:'Zodiac' },
    positions:{ ko:['나 자신','가진 것','주고받는 말','가정과 뿌리','사랑과 즐거움','일과 일상','파트너','변화와 이면','넓히는 것','사회에서의 자리','사람과 무리','감춰진 것'], en:['Yourself','What you hold','Words exchanged','Home and roots','Love and play','Work and routine','Partners','Change and the hidden side','What widens you','Your place in the world','People and circles','What is concealed'] } },
};
